### ISSUE TITLE
Problem compiling to prod (but works on dev)

### ISSUE THREAD

**Issue by gdub01** [jedwards1211/meteor-webpack-react#103]
When trying to run node dev.js I have no errors and the app runs fine. However, when I run node prod.js I get the below error for that '@' symbol:

ERROR in ./app/routes/App.js
Module build failed: SyntaxError: /Users/Gavin/websites/saas/app/routes/App.js: Unexpected token (10:0)
   8 | import styles from './app.css';
   9 |
> 10 | @reactMixin.decorate(ReactMeteorData)
     | ^
  11 | export default class App extends Component {
  12 |   static propTypes = {
  13 |     params: PropTypes.object
    at Parser.pp.raise (/Users/Gavin/websites/saas/node_modules/babel-core/node_modules/babylon/lib/parser/location.js:24:13)
....
    at Object.exports.default (/Users/Gavin/websites/saas/node_modules/babel-core/lib/helpers/parse.js:36:18)
 @ ./app/routes/index.js 21:11-27
ln: Source file does not exist

And a second error: (I could potentially change this but I wonder if it's related.)

ERROR in ../app/routes/Plans/index.js
Module build failed: SyntaxError: /Users/Gavin/websites/saas/app/routes/Plans/index.js: Unexpected token (1:7)
> 1 | export List from './List';
    |        ^
  2 | export View from './View';
  3 | export Create from './Create';

Appreciate any help.

**Comment by davidnussio** [comment]
Change babel configuration into webpack/webpack.config. and add:

query: { stage: 0}

**Comment by gdub01** [comment]
Thanks so much! Worked great.
