### ISSUE TITLE
Redundant configs?

### ISSUE THREAD

**Issue by rclai** [jedwards1211/meteor-webpack-react#108]
In [webpack.config.client.js](https://github.com/jedwards1211/meteor-webpack-react/blob/06f5a3da67ff57389e7d7c8c28434b84a09d687b/webpack/webpack.config.client.js#L27-L30), is the highlighted code duplicated in [webpack.config.client.dev.js](https://github.com/jedwards1211/meteor-webpack-react/blob/06f5a3da67ff57389e7d7c8c28434b84a09d687b/webpack/webpack.config.client.dev.js#L49-L53)?

**Comment by jedwards1211** [comment]
Yep!  Should have checked a PR more carefully

**Comment by jedwards1211** [comment]
This is no longer relevant, since I merged all the config building into one file now
