### ISSUE TITLE
Alternate folder structure

### ISSUE THREAD

**Issue by AdamBrodzinski** [jedwards1211/meteor-webpack-react#11]
I've been tweaking and tuning the setup to work for my personal boilerplate so I thought I would share this in case you want to pull some ideas from it or even do a full PR. My [alt-structure](https://github.com/AdamBrodzinski/meteor-webpack-react/tree/alt-structure) branch has the reformed app. Basically it merges the webpack and meteor folders together and separate the app into `app` and the meteor folder into `meteor_files`. IMHO this makes the whole setup feel more first class as opposed to feeling like two separate projects.

I've also done away with the client/both/server folders. I've been so ingrained with that setup that it seemed right at first... however it makes more sense to have a flat structure with two main files for client & server.

Here's a screen of the folder structure (entire and just app/):

<img width="393" alt="screen shot 2015-08-09 at 5 18 45 pm" src="https://cloud.githubusercontent.com/assets/1445367/9157398/cf73c1ac-3ec9-11e5-95ca-3624a8893661.png">

It also has a bare bones layout for pages and components instead of the todo app.. since that will always have to be deleted. Most apps will have a header/footer/ and home page so these will likely stay most of the time.

Also:

- es lint and lint target (npm run lint)
- scss loader
- require aliases for components, models, etc..
- meteor settings and utils helper
- react-router
- blaze component fix

It also has some super basic CSS (reset, box padding/margin fix, header, page) so that people can look at how to require styles on a per component/page basis.

<img width="377" alt="screen shot 2015-08-09 at 6 19 59 pm" src="https://cloud.githubusercontent.com/assets/1445367/9157409/25a2ff8e-3eca-11e5-8d43-f7bb0b078724.png">

At the very least I think we should merge in the blaze template fix (now never updates) and meteor settings. The rest is opinionated and i'm obviously biased. This setup has worked well for other prod apps (albeit with globals and client/both/server folders lol)  If you like this just let me know what parts to PR. 

Cheers! :beers:

**Comment by jedwards1211** [comment]
Ah cool, yeah I bet you're onto something about the simpler folder structure.  I'll look at this in more detail tomorrow.  I could just make the simple todos example a branch so that the master is just a skeleton like this.
Personally I like to put little style files in the same folder as my components.   That way inside `Collapse.jsx` for example I can just `require('./Collapse.sass')`.
And yeah, I hadn't messed with getting ES lint working, cool.
I've enjoyed refining this with you!

**Comment by AdamBrodzinski** [comment]
Cool, glad you like it! I also have my component styles in the same folder. The styles folder in the root just has global things like 'reset', 'layout', colors, etc... I'm not sure i'm requiring them the best way but in the component it's just `import './Header.scss';`

I've enjoyed it too, I love tinkering and customizing my build and webpack does that and then some :laughing: If you're ever in the Bay area the beers are on me!

Would you be opposed to adding Karma so that basic react component unit tests are passing? I have a pretty nice setup that's worked really well (should also be smaller with modules):
https://gist.github.com/AdamBrodzinski/aeb5b669a74259da8af8
 https://medium.com/@skinnygeek1010/unit-test-react-components-in-meteor-a19d96684d7d

**Comment by jedwards1211** [comment]
Yeah, adding Karma would be good.  I'd rather we leave out any particular CSS and empty folders because if I were starting a new project with this skeleton I would probably just delete those and do something else (plus the sites I've worked on don't have that layout ;), so I figure plenty of other people would.  I just want to have the minimum structure necessary to get everything up and running.  But of course you could easily maintain a branch or fork with your folder structure and merge from the master of this project when we make changes in the future.

**Comment by jedwards1211** [comment]
Oh and I don't foresee being in the Bay area unless a new job requires me to, but thanks for the invitation!  If I am I'll definitely let you know!

**Comment by AdamBrodzinski** [comment]
Ok cool i'l add the karma stuff later this week. Did you want me to PR the basic project structure with the following? I couldn't tell if you were referring the the opinionated layout of `app/*` or just the general project layout of one folder (as opposed to webpack/meteor at the root). IMHO for this repo it's better to just have a fairly empty app folder with something like below... thoughts?

```
app
  components/
     BlazeTemplate.jsx
     App.jsx
  main_client.js
  main_server.js
assets
meteor_files
meteor_settings
...
```

**Comment by madshargreave** [comment]
I'm curious, what the motivation for leaving out the both/server/client folders?

**Comment by jedwards1211** [comment]
@AdamBrodzinski I was talking about the `app/*` folder.
@madshargreave I like the idea of leaving out those folders because it just means a bit less typing in `import ... from ...` statements.  I also like having the webpack stuff/`package.json` be in the root of the project with Meteor in a subfolder because all of the run scripts are executed from the folder containing `package.json`.

**Comment by madshargreave** [comment]
I see, where would you put business logic (say Meteor.methods), that should not be sent down to the client?

**Comment by jedwards1211** [comment]
You could put it in the `main_server.js`, something that file requires, basically anywhere that gets pulled into the webpack server bundle but not the client bundle.

**Comment by AdamBrodzinski** [comment]
> I see, where would you put business logic (say Meteor.methods), that should not be sent down to the client?

@madshargreave To further elaborate.... ***no files are executed by default*** with the exception of the main_server.js and main_client.js. These are the only two files that get moved over to the client and server. This is a change compared to Meteor which will execute every file in a weird alphabetical order (hence all the client/server/lib/ folders). The module is executed once on it's first require and then is accessible any other nth time another file needs it (as far as I understand)

*Any module* is capable of being sent to the client or server, so it doesn't make sense to put them in a client/server folder. You certainly *could* do this but Webpack doesn't copy/paste the entire folder like one might think at first. So if you have a file in 'client/log' then the server could easily import it with `import "./client/log"`. If it helps you organize then that's great!

Basically the main_server.js is the only file that gets sent to the server. To get additional files to the server, main_server.js would have to require that module.

The same goes with client files. main_client.js might only require router.js Then router.js will require all the pages it needs. Those pages will require the files they need. Only the files needed get sent used.

This is a bit weird if you've never worked with Node or other modern web builds. It took me a few mins to wrap my head around it because i've spent a while doing things the global way.

There's also another edge case that can catch you off guard. If you want to execute a file that's never used, you need to `import "./methods/userMethods";` to execute and initialize the code 

Meteor methods must be defined on the sever. If we're never using the method file on the server then it won't get executed and the client call will fail with a missing method error. This is an easy fix. 

```javascript
// in server_main.js file

import "./methods/users";
import "./methods/comments";

// or most of the time you're using the exported variable like this
import log from  "./utils/logger";

log("Hello World");


```

Then if you require the Meteor method files on the client it will make them a stub so you have latency compensation.

Since we have a nice way to require Meteor methods you can also export an facade when importing the Meteor method file. Here's an example of that with a 'User model' (totally optional, you can still use the global Meteor.call):
`User.sayHi('Hello")  >>>  Hello superman`
https://github.com/AdamBrodzinski/meteor-webpack-react/blob/alt-structure/app/models/user.js

Does this make sense? I'm going to write a guide (and screencast) soon once things are ironed out so I would def. appreciate any feedback :+1:

**Comment by AdamBrodzinski** [comment]
Much more slimmed down now! Here's the app folder:

```
.
├── collections
│   ├── posts.js
│   └── users.js
├── components
│   ├── App.css
│   ├── App.jsx
│   └── BlazeTemplate.js
├── fixtures.js
├── main_client.js
├── main_server.js
└── method_example.js
```

We could remove the method example, fixtures, and posts collection files but I think they help address the following:

- using a collection with webpack/es6
- fixtures show how to use Meteor global
- methods file show how to share code on both, creating a stub on client and define on sever

Here's the new branch, didn't have time to re-apply the new changes from this repo:
https://github.com/AdamBrodzinski/meteor-webpack-react/tree/minimal

I don't want to get too crazy here but I was thinking.. it may be even easier on the user to put all of the webpack stuff in one webpack folder. Do you think this would be helpful or more annoying? If not, would leaving the scripts folder out into the root be helpful? 

```
app/
builds/
meteor_core/
meteor_settings/
webpack_server/
  ├── scripts/
  ├── assets/
  ├── webpack.config....
package.json
.eslintrc

```

**Comment by grigio** [comment]
I agree, maybe it could be a little bit nicer with `index.js` in the folder, similar to [this](https://github.com/callemall/material-ui/blob/master/src/ripples/index.js), so you can simplify the import rows.

```
├── collections
│   ├── index.js
│   ├── posts.js
│   └── users.js
```
```
// somewhere else
import { Users, Posts } from "./collections/index.js"
```

**Comment by AdamBrodzinski** [comment]
Interesting! You could even shorten it more with `import { Users, Posts } from "./collections"` since it will look for `.index.js`. This could grow into a very large file if you have a lot of collection helpers for denormalizing but I think for the boilerplate an index would better because it's less to delete and shows you how to use `index.js`.

I also forgot to remove the aliases.... with those you could shorten the above by not using the relative path using  `import { Users, Posts } from "collections"` from any directory.

**Comment by jedwards1211** [comment]
@grigio  you can shorten that to `import { Users, Posts } from './collections'`  If you put import from a folder, Webpack first looks for `index.js` in it :)

**Comment by jedwards1211** [comment]
Man I really need to get better about patiently reading everyone's comments.  I just said the same thing before reading that you did Adam.

I'm trying to think of the impacts of having the webpack stuff/scripts folder in the root vs. a webpack folder (I think calling it `webpack_server` might confuse people because it's building both the client and server bundles), but I can't see any big differences.  Maybe if one ever needs to manually launch webpack in the root folder it would be good to have the files there, although I doubt that's a common use case.

**Comment by AdamBrodzinski** [comment]
Ah, yea `webpack_server` is a bit overloaded. `webpack` would be better. 

> Maybe if one ever needs to manually launch webpack in the root folder it would be good to have the files there, although I doubt that's a common use case.

So if you're in the root folder, you should still be able to run webpack from the root with `npm run dev` though, correct? (assuming the paths are updated) Or did you mean manually running `webpack --config webpack.config.server.js --watch`? Either way I think it would be easy enough if all the webpack stuff was tucked in a `webpack/` folder. Just my $0.02 :smiley: 

Hoping to rebase changes and push the latest tonight.... unless I just jinxed myself :laughing:

**Comment by jedwards1211** [comment]
yeah, `npm run dev

**Comment by AdamBrodzinski** [comment]
Cool sounds good, I won't get to it until tonight at best anyway :+1:

**Comment by grigio** [comment]
@AdamBrodzinski meteor_core or meteor_app sounds natural to me

**Comment by jedwards1211** [comment]
@AdamBrodzinski what is the different between those two folders again?  I would prefer if the one from which Meteor is run is just called

**Comment by jedwards1211** [comment]
whoops

**Comment by AdamBrodzinski** [comment]
closing now that this is merged

**Comment by jedwards1211** [comment]
Ah, so the fact that now entry paths inside the webpack configs are no longer relative to the config files, to me it's awkward to work with.  I will probably change the scripts to cd to the webpack folder so that the webpack configs can use relative paths as usual

**Comment by AdamBrodzinski** [comment]
Oh yea that sounds better... I was wondering why I didn't run into that before... that must have been it. It's super awkward determining where what dir you're currently in.

**Comment by jedwards1211** [comment]
yeah, the paths in the `entry` section unfortunately don't work like `require()` paths do
