### ISSUE TITLE
page showing 0 posts and 0 users although the fixtures should have populated the dummy posts and users

### ISSUE THREAD

**Issue by gavriguy** [jedwards1211/meteor-webpack-react#111]
Hi,
I have a question.
I downloaded the repo and run `node dev.js`
On the server log I get that there are 4 posts, but on the client I get 0. any idea what am I doing wrong?
<img width="554" alt="todo list" src="https://cloud.githubusercontent.com/assets/119617/10867697/e2a5a06a-8078-11e5-94ed-0af839e7ae77.png">

**Comment by davidnussio** [comment]
I think is running without autopublish. Install it or pub/sub...

**Comment by AdamBrodzinski** [comment]
Yep you just need to add a publication on the server and subscribe on the client. I should prob. change (autopublish removed)  to (autopublish removed, add publication in to get count) or something.

**Comment by gavriguy** [comment]
cheers 10x
+1 for (autopublish removed, add publication in to get count) or for adding autopublish by default
