### ISSUE TITLE
Is this production ready?

### ISSUE THREAD

**Issue by madshargreave** [jedwards1211/meteor-webpack-react#112]
Hi

Has anyone experience using this approach in a production environment?

**Comment by AdamBrodzinski** [comment]
Yep! I've been using in prod in a couple of apps for about 2 months now. Works great!

**Comment by tomitrescak** [comment]
Me as well, all works great!

**Comment by jedwards1211** [comment]
Aehmmm, the current master has some issues.  I've been pretty busy lately :/  There are two working options right now:
* https://github.com/jedwards1211/meteor-webpack-react/tree/webpack-meteor-tools branch (probably best)
* Use release 0.1.0 (the only release so far)

**Comment by grigio** [comment]
@jedwards1211 Argh.. I've tried both but I get missing stuff (Npm) or missing deps

**Comment by jedwards1211** [comment]
Shoot.  Maybe I can find time to clean things up this weekend

**Comment by darkadept** [comment]
I've been working off the `webpack-meteor-tools` branch with success. I couldn't get `master` to work for me and like you said it has some issues.

I've been trying to follow what the changes are between those two branches but I'm not enough of a wizard to see it. It seems like `webpack-meteor-tools` has the *webpack-meteor-tools* NPM package included (duh) but the master branch has moved away from grunt for building. I've played a bit with merging them but can't get it to work out.

**Comment by jedwards1211** [comment]
@darkadept there was never a grunt build, just shelljs scripts. The `webpack-meteor-tools` branch uses some things in the `webpack-meteor-tools` npm package to copy the webpack bundles to Meteor, rather than the shelljs scripts doing that.

**Comment by roberto68** [comment]
master works for me fine - but I just run it as is.

**Comment by jedwards1211** [comment]
I'm closing this as I finally fixed up a bunch of issues with the master branch recently
