### ISSUE TITLE
Best approach to separate client and server code?

### ISSUE THREAD

**Issue by madshargreave** [jedwards1211/meteor-webpack-react#113]
Hi

What is the best way to separate client and server code? Right now, it just seems they're all in the same place, and it is only when they're required, that it becomes obvious where they're used

**Comment by davidnussio** [comment]
My purpose with these kinds of projects is to minimize as much as possible the separation client / server

**Comment by ramsaylanier** [comment]
For me, I use the single main_server.js file and import stuff like Meteor Methods, publications, and accounts configuration. All of the startup stuff that happens server-side is handles inside of that one file.

**Comment by AdamBrodzinski** [comment]
@madshargreave You can move the code into any folder you'd like. For example you can move publications into `/server/publications` and subscriptions in `/client/subscriptions`. You could even move common code into a `both` folder if that makes more sense for your project.

Then in your imports you'd just `import foo from 'server/publications/foo';`.

**Comment by rclai** [comment]
You should also take a look at how I imported the scripts of an entire folder [here](https://github.com/jedwards1211/meteor-webpack-react/issues/77#issuecomment-146292015).

**Comment by jedwards1211** [comment]
To add to what people have said above, there are some cases where most but not all functionality of a module is the same on the client and server.  In that case I use `Meteor.isServer` and `Meteor.isClient` blocks within the same file, and use Webpack's `DefinePlugin` + UglifyJS to magically remove the server blocks from the client bundle and vice versa.

**Comment by jedwards1211** [comment]
I'm going to close this but feel free to keep discussing
