### ISSUE TITLE
How to include a CSS framework?

### ISSUE THREAD

**Issue by madshargreave** [jedwards1211/meteor-webpack-react#114]
Hi

How can I include a CSS framework such as Semantic UI?

**Comment by tomitrescak** [comment]
You have several options:

1. Include it in meteor_core as meteor package
2. Add is as npm module and import only what is necessary

I went with option 2, added semantic-ui-css package and imported only those css and js that I needed.
e.g. import 'semantic-ui-css/components/site.css'

You can do similar with less

**Comment by jedwards1211** [comment]
If Semantic UI is actually compiled from Sass or Less or whatever (I don't know) then I'd recommend option 2, because you may also want to include variables from it to use in your own Sass/Less/etc. files, and option 2 would allow you to do that without any redundancy.

**Comment by rozzzly** [comment]
It uses less. As somebody who has preexisting code in scss, this makes me _less_ than happy.

**Comment by jedwards1211** [comment]
Hahahaha.  Well you know, someone converted all of Bootstrap to Sass... I think they have an automatic converter for it.  Maybe people will do that with Semantic UI someday.  Maybe someone will even make a magic load-less-as-sass loader for Webpack someday!

**Comment by AdamBrodzinski** [comment]
Bootstrap 4 is even using Scss in core now :laughing:

**Comment by jedwards1211** [comment]
Huh.  Why not just Sass, I wonder?

**Comment by rozzzly** [comment]
no python-esq indent-dependant syntax? That's what got me to jump over. That and because scss is _the hip new thing_. :wink:

**Comment by jedwards1211** [comment]
Hahahaha, interesting.  I had never thought about it but this article I found does bring up a lot of interesting points: http://thesassway.com/editorial/sass-vs-scss-which-syntax-is-better

Although I thought PostCSS was the hip new thing? :smiley:

**Comment by AdamBrodzinski** [comment]
Wat?? When did this come out? I must be getting old :laughing:

I'm so ready for JS based styles.... it's the hover/active/etc type styles that have me a little uneasy... It works really great in ReactNative.
