### ISSUE TITLE
babelHelpers is not defined

### ISSUE THREAD

**Issue by rclai** [jedwards1211/meteor-webpack-react#12]
I created a fresh install on dev mode. When I loaded the page, I got this on my console:

```
[HMR] Waiting for update signal from WDS...
meteor-data-mixin.jsx.js?fa4d1f3defe065ca62fd3e0ac3211e558fd74325:40
Uncaught ReferenceError: babelHelpers is not definedMeteorDataManager
@ meteor-data-mixin.jsx.js?fa4d1f3defe065ca62fd3e0ac3211e558fd74325:40ReactMeteorData.componentWillMount
@ meteor-data-mixin.jsx.js?fa4d1f3defe065ca62fd3e0ac3211e558fd74325:4(anonymous function)
@ makeAssimilatePrototype.js:15ReactCompositeComponentMixin.mountComponent
@ ReactCompositeComponent.js:228ReactPerf.measure.wrapper
@ ReactPerf.js:70ReactReconciler.mountComponent
@ ReactReconciler.js:38mountComponentIntoNode
@ ReactMount.js:248Mixin.perform
@ Transaction.js:134batchedMountComponentIntoNode
@ ReactMount.js:269Mixin.perform @ Transaction.js:134ReactDefaultBatchingStrategy.batchedUpdates
@ ReactDefaultBatchingStrategy.js:66batchedUpdates
@ ReactUpdates.js:110ReactMount._renderNewRootComponent
@ ReactMount.js:404ReactPerf.measure.wrapper
@ ReactPerf.js:70ReactMount.render
@ ReactMount.js:493ReactPerf.measure.wrapper
@ ReactPerf.js:70window.onload
@ index.js:14
[WDS] Hot Module Replacement enabled.
```

**Comment by jedwards1211** [comment]
Ah, my mistake, I had removed the babel package thinking it was unnecessary.  Let me fix it real quick

**Comment by jedwards1211** [comment]
I'm a bit confused how I didn't catch this.  I guess a previously built version of `react-meteor-data` remained after I removed those deps

**Comment by jedwards1211** [comment]
Fix pushed.  Sorry about that!

**Comment by rclai** [comment]
It would kind of suck if we do need that dependency. Makes me want to just copy the mixing code and be done with it.

**Comment by rclai** [comment]
Thanks.

**Comment by AdamBrodzinski** [comment]
@jedwards1211 you might also need to delete the meteor `.meteor/versions` file... sometimes it's sticky and won't upgrade you to the latest.

**Comment by jedwards1211** [comment]
Oh, if you delete it then Meteor will repopulate it on the next run?

**Comment by jedwards1211** [comment]
You guys probably have more Meteor experience than I do, so if I do something foolish on the Meteor side of things feel free to correct me.

**Comment by AdamBrodzinski** [comment]
> Oh, if you delete it then Meteor will repopulate it on the next run?

Yep, sometimes I do that when I don't care about locking the version... sort of like deleting the gem lock file. There's also an id file in `.meteor` that we should delete eventually... it basically tracks the app when deploying to meteor.com servers. It's a pain though because you can't gitignore it but ideally shouldn't check it in for a boilerplate.

> You guys probably have more Meteor experience than I do, so if I do something foolish on the Meteor side of things feel free to correct me.

Will do! I think you've done a great job so far. I've used it for the last 2-3 years on startup companies and wrote tens of thousands of lines of Meteor code and it's hard to catch all the little things unless you've been bitten by it before (I have many times :laughing: )
