### ISSUE TITLE
Verbose output

### ISSUE THREAD

**Issue by AdamBrodzinski** [jedwards1211/meteor-webpack-react#120]
Just wondering if you know how to make the output less verbose when there isn't an error? Every build floods my terminal and i've noticed that a new non-meteor project using the hot boilerplate doesn't do this. For the life of me I can't get some of the configs in the docs to work :frowning: 

<img width="645" alt="screen shot 2015-11-25 at 7 55 00 pm" src="https://cloud.githubusercontent.com/assets/1445367/11412759/910a6cc4-93ae-11e5-9dd2-b834843c6dd6.png">

**Comment by jedwards1211** [comment]
Yes, I do happen to know a solution to this!  I will commit soon

**Comment by AdamBrodzinski** [comment]
:+1: Thanks!
