### ISSUE TITLE
Wallaby

### ISSUE THREAD

**Issue by tomitrescak** [jedwards1211/meteor-webpack-react#121]
Guys, I've bumped into Wallaby.js, a very awesome testing tool for javascript applications. Runs fast and it integrates into most editors. They have some examples for webpack, but even after hours I have not found a way to make it run. They note that all they need is a source file with sourcemap (which you deliver) and then they can automatically postprocess it with webpack postprocessor to get line coverage and test results. Coming to think of it, it should not be a big problem to make it run ... I'll report back if I'll find out more, otherwise if you could help I'd be really greatful! ;)

**Comment by tomitrescak** [comment]
Here is some more info: http://wallabyjs.com/docs/integration/webpack.html

**Comment by AdamBrodzinski** [comment]
That's pretty cool! Did you make any progress with this? Looking at the Karma runner and webpack config might help.

Closing this out but feel free to re-open or continue the convo, I always love to see new test stuff!
