### ISSUE TITLE
Calling configure method of useraccounts package causes error

### ISSUE THREAD

**Issue by funkybunky** [jedwards1211/meteor-webpack-react#125]
Basically the question is probably where to place calls that run before Meteor.startup(), but I'm not 100% sure..
I installed the useraccounts package as described in their guide, but when I try to set the options with `AccountsTemplates.configure(options)` I get this error: 
`Uncaught Error: Configuration options must be set before AccountsTemplates.init!`
Where should I set those options that they run before the call to the init function happens? Did anyone run into this?
The use-case: I want to add custom routing hooks so I can use the package with react-router. Any experiences in that regard are also greatly appreciated ;)
And I just pulled the current version of master.

**Comment by AdamBrodzinski** [comment]
> Basically the question is probably where to place calls that run before Meteor.startup(), but I'm not 100% sure..

They need to go in `meteor_core` preferably in a `lib` folder. All of the webpack code will run too late.

**Comment by AdamBrodzinski** [comment]
Closing to keep issues down but feel free to keep this thread going if you have more questions.
