### ISSUE TITLE
Why would dev.js build server only??

### ISSUE THREAD

**Issue by genyded** [jedwards1211/meteor-webpack-react#127]
Not sure anyone is even monitoring this repo anymore, but initial install and build went fine, but only server is build (even though output says client was too)...

![scriptsfromhell](https://cloud.githubusercontent.com/assets/3081676/11765786/11a20096-a12d-11e5-9195-538ae1000f67.png)

Yes I am on Windows... but there is no client bundle in the assets folder to copy over or rename so I do not think that is the issue.

**Comment by tomitrescak** [comment]
Check out my last post in #99 

That's how I managed to get this project to run on Windows.
Worked nicely afterwards

**Comment by genyded** [comment]
Saw that and got it working finally - thanks!
