### ISSUE TITLE
npm WARN deprecated lodash@0.9.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0 npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0

### ISSUE THREAD

**Issue by roberto68** [jedwards1211/meteor-webpack-react#131]
apparently there are some packages which have have the old lodash as the dependency

**Comment by roberto68** [comment]
ok so it issue of grunt whcih uses grunt-legacy-utils which have the old lodash (0.9.2), but with npm list lodash I was unable to trace what requires the 1.0.2 version.

**Comment by wdhorton** [comment]
I wouldn't worry about this too much, since it's a warning rather than an error. This isn't an issue with this project, it's an issue with one of the packages it depends on, so I don't think there's much to be done.

**Comment by jedwards1211** [comment]
I just updated to the latest lodash in [release 1.1.0](https://github.com/jedwards1211/meteor-webpack-react/releases/tag/1.1.0)
