### ISSUE TITLE
TypeError: Cannot read property 'loginButtons' of undefined

### ISSUE THREAD

**Issue by jrothman** [jedwards1211/meteor-webpack-react#132]
I've followed the steps as outlined in the readme.md to try and perform a dev build but I'm getting errors once the server/Meteor starts running - see my versions + steps followed + outputs below:
I'm sure someone must have solved this, so any guidance would be appreciated.

Ubuntu 15.10
node -v
v4.2.4
npm -v
2.14.12
meteor
1.2.1

git clone https://github.com/jedwards1211/meteor-webpack-react.git
cd meteor-webpack-react

~/Dev/meteor-webpack-react$ sudo npm install

~/Dev/meteor-webpack-react$ sudo node dev.js
core-js@1.2.6 without ES6 number constructor is up to date
Hash: 948f9a2428f4c4787a41  
Version: webpack 1.12.9
Time: 1918ms
               Asset     Size  Chunks             Chunk Names
    server.bundle.js   893 kB       0  [emitted]  main
server.bundle.js.map  1.01 MB       0  [emitted]  main
chunk    {0} server.bundle.js, server.bundle.js.map (main) 819 kB [rendered]
Hash: 2492ce94ad9053ae68ad  
Version: webpack 1.12.9
Time: 2120ms
           Asset     Size  Chunks             Chunk Names
client.bundle.js  1.36 MB       0  [emitted]  main
chunk    {0} client.bundle.js (main) 1.12 MB [rendered]
webpack: bundle is now VALID.
[[[[[ ~/Dev/meteor-webpack-react/meteor_core ]]]]]

=> Started proxy.
=> Meteor 1.2.1 is available. Update this project with 'meteor update'.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
I20151229-10:51:50.982(2)? undefined
I20151229-10:51:50.983(2)? 
I20151229-10:51:50.983(2)? 
I20151229-10:51:50.983(2)? Running on server only
I20151229-10:51:50.983(2)? There are # posts: 4
I20151229-10:51:50.983(2)? React SSR: `<div class="App" data-reactid=".izkk0o54w0" data-react-checksum="2009644989"><div data-reactid=".izkk0o54w0.0"></div><h1 data-reactid=".izkk0o54w0.1">Hello Webpack!</h1><p data-reactid=".izkk0o54w0.2"><span data-reactid=".izkk0o54w0.2.0">There are </span><span data-reactid=".izkk0o54w0.2.1">3</span><span data-reactid=".izkk0o54w0.2.2"> users in the Minimongo  (login to change)</span></p><p data-reactid=".izkk0o54w0.3"><span data-reactid=".izkk0o54w0.3.0">There are </span><span data-reactid=".izkk0o54w0.3.1">4</span><span data-reactid=".izkk0o54w0.3.2"> posts in the Minimongo  (autopublish removed)</span></p></div>`
W20151229-10:51:50.988(2)? (STDERR) Warning: React.renderToString is deprecated. Please use ReactDOMServer.renderToString from require('react-dom/server') instead.

Browser output at http://127.0.0.1:3000
TypeError: Cannot read property 'loginButtons' of undefined
render
~/Dev/meteor-webpack-react/app/components/App.jsx
...

**Comment by YuHuaiChen** [comment]
I think some folks mentioned that master branch currently has some problems.

You should use the  `webpack-meteor-tools` branch instead!

**Comment by jrothman** [comment]
Thanks - tried that and managed to get it to compile and run.

**Comment by wdhorton** [comment]
I ran into the same error, just submitted PR #135 to fix it. Other than that, master is running fine for me.

**Comment by jedwards1211** [comment]
I just cleaned up a bunch of things in `master`...the hack people had made to monkeypatch `Template` on the server side was affecting the client-side namespace, so I just wrapped that part of the rendering in a `Meteor.isClient`.  I'll be more careful about PRs from now on...
