### ISSUE TITLE
mailgun-js 

### ISSUE THREAD

**Issue by elliott-vorel** [jedwards1211/meteor-webpack-react#134]
Has anyone had luck using mailgun-js? (https://github.com/mailgun/mailgun-js)

It is build with webpack using es6. I get the error SyntaxError: Unexpected reserved word 
at 'class Client {' but I cannot seem to figure out why. 
What changes are needed to the current webpack configuration?

**Comment by yourcontainer** [comment]
I use https://github.com/cunneen/meteor-mailgun for my project, all works fine

**Comment by jedwards1211** [comment]
@elliott-vorel the webpack config excludes anything in `node_modules` from being transpiled by Babel, that's why you're seeing the problem.  You have to add a rule to specifically use Babel on it:
```js
        ...
        {
          test: /\.js$/,
          loader: 'babel',
          include: /node_modules\/mailgun/,
        },
        ...
```
