### ISSUE TITLE
Adding loaders to webpack.config.client.js

### ISSUE THREAD

**Issue by tobias-f** [jedwards1211/meteor-webpack-react#137]
Hello.

It seems that if I add a new loader (e.g. the less loader) to the webpack.config.client.js file and run npm dev.js, the new loader definition gets overwritten by the loader definitions in the webpack.config.client.dev.js.
So do I always have to include the loaders in both files? My impression was, that everything defined in webpack.config.client.js should be available across all environments. Am I wrong?

Thanks a lot...

tobias

**Comment by jedwards1211** [comment]
Ah...I didn't notice that a PR I merged doesn't concat the loaders from the `webpack.config.client.js` as it should.  Let me change that.

**Comment by jedwards1211** [comment]
okay, I revamped how the webpack config is created.  Should be much easier to edit now!
