### ISSUE TITLE
Trying to bundle a pure node.js application

### ISSUE THREAD

**Issue by tomitrescak** [jedwards1211/meteor-webpack-react#145]
Hi, some time ago I was using this repo for my meteor projects. Some time ago I switched to pure node.js _ react. Currently I'm trying to deploy my app to server and I remembered your repo.

My goal is to bundle both client and server into two separate files and deploy it to server. Client is easily done with webpack, but for the love of god I cannot figure out how to bundle a simple express app.

When I bundle it, I get `Error: secure random number generation not supported by this browser
use chrome, FireFox or Internet Explorer 11`. bviouslyit bundles incorrectly. 

I know you are a very busy man, so if you find a bit of time would you care to give a bit of advice?

Here is my config:

```js
var webpack = require('webpack');

module.exports = {
  context: __dirname,
  devtool: 'eval',
  entry: [
    './index.js'
  ],
  output: {
    filename: 'bundle.js',
    publicPath: '/public'
  },
  resolve: {
    extensions: ['', '.js', '.json'],
  },
  module: {
    loaders: [
      {
        test: /\.css$/,
        loader: 'null-loader'
      },
      {
        test: /\.json$/,
        loader: 'null-loader'
      }
    ]
  },
  plugins: [
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify('production')
    }),
    new webpack.NoErrorsPlugin(),
    new webpack.optimize.DedupePlugin(),
    new webpack.optimize.UglifyJsPlugin({
      compress: { warnings: false }
    }),
    new webpack.optimize.AggressiveMergingPlugin(),
    new webpack.optimize.OccurenceOrderPlugin(true)
  ]
}
```

**Comment by jedwards1211** [comment]
Huh, it sounds like you're using some package that does secure random number generation but is only designed to work in web browsers, not in node.  Do you have any idea what package that would be?

Some recommendations:
* **Add `target: 'node'` to your config (very important)**
* Get rid of UglifyJS, aggressive merging, and occurrence order plugins -- those are mainly useful to optimize the size of the bundle delivered to the client.  On the server side, there's little benefit to doing that, and it makes debugging more difficult.

In the larger picture though, I'd say it's best to avoid bundling server code with Webpack unless you absolutely have to.  The main reason I use it with Meteor is to get full import/export on the server side (obviously Meteor 1.3+ supports that natively, but I don't trust their bundler nearly as much as Webpack).  Here are the pros and cons:

Pros:
* Server code is single file that's easy to deploy
* Build is highly customizable
  * you can use webpack loaders
  * you can use special plugins like `ProvidePlugin`, `DefinePlugin`, etc.
Cons:
* Debugging is more convoluted, you have to use something like `source-map-support` to see your source files in `node-inspector` and get stack traces relative to your source files
* Build configuration requires more effort to maintain

Having to copy all of the source files to the server would be annoying, but there are several ways to make it easier:
* Use `rsync`
* Use `git` and `git clone` the repo on the server, then `git pull` or `git checkout <tag>` on the server to get the code you want to run
* Use Docker (here's a good guide to dockerizing a node app: https://nodejs.org/en/docs/guides/nodejs-docker-webapp/)

I think it's possible to accomplish the same thing as `null-loader` without Webpack using Babel with a custom resolver.

Btw, check out the `piping` package; it automatically restarts your node app whenever you change any source file, even if you're not using webpack.

**Comment by jedwards1211** [comment]
I'll close this since it's not relevant to this project but I'm happy to keep discussing it!
