### ISSUE TITLE
Module app alias or some aliases?

### ISSUE THREAD

**Issue by grigio** [jedwards1211/meteor-webpack-react#19]
Currently some common files are required with relative notation, my proposal is to use the `app/*` alias or some aliases for some common imports (e.g collections), however this change won't forbid you to continue to require the files with relative path.

```
// main_server_js
import {Posts} from './collections';
...
// main_server_js
import {Users, Posts} from '../collections';
```
after
```
// main_server_js
import {Posts} from 'app/collections';
...
// main_server_js
import {Users, Posts} from 'app/collections';
```

**Comment by grigio** [comment]
#20

**Comment by jedwards1211** [comment]
Makes sense, thanks!

**Comment by AdamBrodzinski** [comment]
I like it, much easier to read! :+1:
