### ISSUE TITLE
./prod production.. Minified exception

### ISSUE THREAD

**Issue by grigio** [jedwards1211/meteor-webpack-react#24]
```
./build
./met deploy mysite
```

I get in the browser console
```
Uncaught Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
```

**Comment by AdamBrodzinski** [comment]
Hmm it worked for me before. I'll try it later on again. I didn't have to do the build though.... If I remember you can do a `./prod` first to switch the folder names and then shut it down and then 
 `./met deploy foo --settings ../settings/devel.json`.

**Comment by grigio** [comment]
If i remember correctly ./prod worked fine

**Comment by grigio** [comment]
argh.. `./dev` doesn't fail, `./prod` fails. It's impossible to debug! :O
I tried to disable some optimization plugins in `webpack.config.client.prod.js` but the error doesn't change

**Comment by jedwards1211** [comment]
Okay, which plugins did you disable?  Most important of course would be UglifyJs and DefinePlugin that sets `process.env.NODE_ENV`

**Comment by grigio** [comment]
I've disabled uglify and unset NODE_ENV
```
Uncaught Error: Invariant Violation: _registerComponent(...): Target container is not a DOM element.
```

**Comment by AdamBrodzinski** [comment]
Hmmm sounds like the `#root` div isn't being found. Wondering if it's missing or mounting before Meteor is ready?

**Comment by jedwards1211** [comment]
I don't guess HTML minification somehow breaks this?

**Comment by grigio** [comment]
@AdamBrodzinski thanks, with `React.render` it also work in production mode
```
Meteor.startup(function (argument) {
    React.render((
```

**Comment by jedwards1211** [comment]
Ah, yeah, I should fix this in `main_client.js`.  Using `window.onload` wasn't very wise.  Sorry about that!

**Comment by jedwards1211** [comment]
Reopening till I fix `main_client.js` to do that

**Comment by jedwards1211** [comment]
okay, just commited a change for that
