### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by AdamBrodzinski** [jedwards1211/meteor-webpack-react#28]
Doh.... I was recording a video tutorial on how to use webpack and ran into a blocker :frowning: 
If I checkout master and run `npm install` then `./dev` it fails at the end 

```
ERROR in multi main
Module not found: Error: Cannot resolve 'file' or 'directory' ../lib/core-js-no-number in /Users/adam/Desktop/meteor-webpack-react/webpack
 @ multi main
webpack: bundle is now VALID.
=> Started MongoDB.
=> Exited with code: 8
W20150830-19:06:23.992(-4)? (STDERR)
W20150830-19:06:23.994(-4)? (STDERR) /Users/adam/.meteor/packages/meteor-tool/.1.1.4.1uwzp7a++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150830-19:06:23.994(-4)? (STDERR) 						throw(ex);
W20150830-19:06:23.994(-4)? (STDERR) 						      ^
W20150830-19:06:23.994(-4)? (STDERR) Error: Cannot find module "../lib/core-js-no-number"
W20150830-19:06:23.994(-4)? (STDERR)     at webpackMissingModule (app/server/server.bundle.js:47:43)
```

The lib folder is created but empty. I also tried to manually run the core-js-custom-build script but that also fails with:

```
meteor-webpack-react|master ⇒ ./core-js-custom-build
Building core-js@1.1.3 without ES6 number constructor...

> phantomjs@1.9.18 install /Users/adam/Desktop/meteor-webpack-react/node_modules/babel-core/node_modules/core-js/node_modules/phantomjs
> node install.js

Looks like an `npm install -g`; unable to check for already installed version.
Download already available at /var/folders/78/h1vhkwqj0jdc47lnb_ymqx8c0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip
Extracting zip contents
Removing /Users/adam/Desktop/meteor-webpack-react/node_modules/babel-core/node_modules/core-js/node_modules/phantomjs/lib/phantom
Copying extracted folder /var/folders/78/h1vhkwqj0jdc47lnb_ymqx8c0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1440976465329/phantomjs-1.9.8-macosx -> /Users/adam/Desktop/meteor-webpack-react/node_modules/babel-core/node_modules/core-js/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /Users/adam/Desktop/meteor-webpack-react/node_modules/babel-core/node_modules/core-js/node_modules/phantomjs/lib/phantom/bin/phantomjs
./core-js-custom-build: line 12: grunt: command not found
```

Is there any way to just build it and commit the file to the repo? I like the idea of having the latest but if it's going to be brittle I think having a default polyfill file would be best and they can always do a custom build if they need the bleeding edge.

**Comment by jedwards1211** [comment]
Oh, shoot, the problem is that grunt is globally installed on my system but not yours.  I assume it's relatively easy to just make grunt work as a dependency of the project.  Or I could just commit the file manually.  But I'm trying to avoid the meteor way where packages have to keep manually updating to the latest version of a given NPM dependency...

**Comment by jedwards1211** [comment]
In any case `npm install -g grunt` should theoretically be a workaround until I get that done.  Let me know if that works

**Comment by thiagoc7** [comment]
`npm install -g grunt-cli` fix the problem... just grunt don't. Cheers!

**Comment by jedwards1211** [comment]
@thiagoc7 oh, good call, thanks!

**Comment by jedwards1211** [comment]
If that commit somehow doesn't work, let me know and I'll reopen this issue.

**Comment by AdamBrodzinski** [comment]
Yep this worked. Thanks!
