### ISSUE TITLE
Use global underscore instead of lo-dash

### ISSUE THREAD

**Issue by AdamBrodzinski** [jedwards1211/meteor-webpack-react#30]
If lo-dash was moved to dev-dependencies, would that omit it when the package is being built? If so that would be ideal since we're already getting underscore for free since Meteor core currently depends on it. I think a good default would be to alias `underscore` to the global one that Meteor provides and the user can always add lodash, Ramda, etc... if needed.

Is this what the webpack [externals](http://webpack.github.io/docs/configuration.html#externals) key is for?

Here's a link to package.json for ref.
https://github.com/jedwards1211/meteor-webpack-react/blob/master/package.json#L24

If this is something that's wanted I can PR tomorrow sometime.

**Comment by jedwards1211** [comment]
The deps are in an awkward state actually, I've been thinking about it.  `dependencies` get installed for an npm package and any packages that depend on it.  `devDependencies` only get installed for the package itself -- only when you `npm install` in that package's folder.  But it would be weird to use this project as an npm package (i.e. `npm install --save meteor-webpack-react`) so I'm thinking we should move all the deps to one or the other.

Webpack `externals` doesn't quite work like that -- rather, if one webpack bundle marks `react` as an external, `react` doesn't get built into that bundle but it's still able to `require` it from the host webpack bundle or something like that (I don't know enough to be technically precise about it).

Webpack as a [resolve.alias](http://webpack.github.io/docs/configuration.html#resolve-alias) option that would work for sharing underscore.  We could do it like this:

`exportUnderscore.js`:
```javascript
export default window._;
```

webpack config:
```javascript
{
  resolve: {
    alias: {
      '_$': path.join(__dirname, './exportUnderscore.js');
    }
  }
}
```

**Comment by jedwards1211** [comment]
Oh yeah, and right now I'm pretty sure lodash is only being used to extend the webpack configs, for instance in [webpack.config.client.dev.js](https://github.com/jedwards1211/meteor-webpack-react/blob/master/webpack/webpack.config.client.dev.js#L3)

**Comment by AdamBrodzinski** [comment]
Oooh right I keep forgetting it doesn't get bundled unless you require it :smile:  

Using resolve for underscore might be useful if you want to do `import {map, reduce} from 'underscore';` though. Not sure if it should be for the boilerplate though. The only part that makes think it should is that Meteor has a hard dependency on it so it'll be available regardless. I guess you could still do `const {map, reduce} = _;`

**Comment by jedwards1211** [comment]
Actually the import syntax probably should work!  Because it would just transpile to something equivalent to `require('underscore').map` etc.  The only problem is requiring internals like `react/lib/...` for instance.

**Comment by jedwards1211** [comment]
Actually, we should be using
```js
externals: {
  'underscore$': {
    root: '_',
  }
}
```
And I think we might as well go ahead and put this in the configs.  I'm busy preparing a prototype for a demo so I don't have much time to fiddle with this project this week, but hopefully next week I can set up releases and get a lot of these issues knocked out.

**Comment by AdamBrodzinski** [comment]
Closing this (unless you think it should still be open), its worth noting that the underscore Meteor uses is super old so using the latest lo-dash offers someone semver, modular builds and more features (what i'm currently doing).

**Comment by jedwards1211** [comment]
Heh, I wonder if they depend on some old behavior that got fixed?  Oh well, probably not that many kb anyway

**Comment by AdamBrodzinski** [comment]
Yea they tried upgrading but minor bumps would break meteor core so it's frozen to a 2013 version lol. They talked about migrating to lodash eventually but it was low on their priorities
