### ISSUE TITLE
Script blows out entire client directory

### ISSUE THREAD

**Issue by AdamBrodzinski** [jedwards1211/meteor-webpack-react#32]
Should the webpack stuff go under another directory if it's going to blow out everything? for example `webpack/client/loadClientBundle.js` and `webpack/server/bundle.js`?

I am in the middle of migrating a legacy Meteor app to webpack and just lost all of my styles and global namespaces that I put in `meteor_core/client/....`. I didn't realize it would be nuked and after I rebooted everything started throwing. I think I got most of it back with Git (kind of hairy staging area at the moment lol)

**Comment by jedwards1211** [comment]
Oh, man, that is dangerous, huh?  I'll just make it delete only specific files.

**Comment by AdamBrodzinski** [comment]
No worries, the price to pay for the bleeding edge :laughing: 

FWIW, it's really not too painful migrating a large-ish app to using this webpack setup. After I nailed down a game plan it was pretty nice.

- move meteor app into /old_app
- expose legacy global namespaces in `meteor_core/lib`
- migrate router (and get hello world working again)
- move my old 'both' folder's subfolders into app/ (components, models, etc..)
- export module for each new file (found this faster than doing each one that throws), using macros and grep in Vim makes this pretty painless
- add eslint `*/ global Meteor, FlowRouter, etc...*/` to top for readability
- resolve undefined errors as you walk the router tree

Still have to figure out how to use Sass global variables with the imported Sass... currently using Meteor to compile sass and using a `../../../../../../` to get back into the app folder lol. Works :smile: 

Not too shabby! (almost done)
