### ISSUE TITLE
Speed up hot-loading

### ISSUE THREAD

**Issue by AdamBrodzinski** [jedwards1211/meteor-webpack-react#33]
The 2 sec hot-load isn't bad but could be better. 

I've done some hacking on my new webpack project and reduced the re-load time down to around 0.8 seconds.... ish. It's getting hard to time it with a stopwatch lol. As I finish the rest of the migration it'll be nice to see what a med sized app will do (currently it's only watching around ~70 files).

I have another 500+ file app around 20k loc that takes 15+ seconds to reload with Meteor... would love to see what this would do lol.

Hoping to be able to PR tonight or tomorrow :+1:

**Comment by grigio** [comment]
Cool, currently I've disabled it. In some situations full reload is faster for me

**Comment by AdamBrodzinski** [comment]
Just pushed the PR. Hot loads with cheap source maps take around 0.6 seconds. With good source maps hot loads are around 1.3 seconds. Perfect source maps is the same at around 2.5 seconds.

Also making sure you exclude node_modules in all of your loaders in crucial.

**Comment by jedwards1211** [comment]
Are you loading bootstrap less/sass in any of your own projects?  I've been wondering how much time of the initial load that eats up in some of my projects

**Comment by AdamBrodzinski** [comment]
I haven't had a chance to do too much Sass with it yet. I have it installed but am not requiring any yet. Once I can figure out how to use global Sass vars I can migrate the last project (I guess you can pass them into the loader somehow).

If you happen to have all of your styles in one place you can use the `include` key in the loader to scope it to one directory.... that should speed it up (or even just the app folder).

I imagine that once the app is first loaded those should be cached so I doubt they would add too much overhead. Is your first load really slow?
