### ISSUE TITLE
Is there any chance to switch MDG to webpack?

### ISSUE THREAD

**Issue by SenerDemiral** [jedwards1211/meteor-webpack-react#39]

**Comment by grigio** [comment]
https://github.com/meteor/meteor/issues/5117

**Comment by jedwards1211** [comment]
I certainly don't know, I'd prefer that they simply rewrite Meteor packages as NPM packages, and then we can use webpack or whatever tool we want with it.

**Comment by SenerDemiral** [comment]
Someday they do, I hope not too long.

**Comment by gdub01** [comment]
I'm not sure if this is the right place to post, but from @AdamBrodzinski dropping mongo for rethinkdb post on meteor forums, there's this https://github.com/GordyD/3reem and this https://github.com/mikemintz/react-rethinkdb project underway. It's not meteor, but I think gives similarish functionality with just normal use of NPM.

**Comment by AdamBrodzinski** [comment]
Interesting! I'll check it out, thanks! I think the latter could actually be used in Meteor alongside the other Meteor stuff.

**Comment by jedwards1211** [comment]
HMMMM....I would not be at all surprised if `rethinkdb` obsoletes Meteor before too long

**Comment by jedwards1211** [comment]
I knew some kind of nice Meteor alternative would come along soon :P

**Comment by AdamBrodzinski** [comment]
I wouldn't be surprised if eventually Phoenix with Elixir & RethinkDB streams overtakes Meteor at some point. Functional programming, Ruby like syntax, and > million concurrent connections per server :stuck_out_tongue_winking_eye: 

It's been my weekend tinkering package lately:  http://www.phoenixframework.org

**Comment by grigio** [comment]
@AdamBrodzinski I don't know, but if you don't use javascript on the server you can't make isomorphic queries anymore. If If you really care about performance, concurrency and new stuff probably also Rust + MIO + Websocket seems cool https://github.com/burrows-labs/mio-websockets

**Comment by AdamBrodzinski** [comment]
@grigio yea I was half joking because Elixir is unfortunately not as popular as Go and Rust (havne't tried Rust yet though i'll checkout the link)

I do think Relay offers a huge threat once they add realtime streaming though, here's a really nice example of isomorphic React + Relay/GraphQL: https://github.com/xpepermint/isomorphic-react-relay-boilerplate

**Comment by jedwards1211** [comment]
I'm closing this to clean out the issues list, feel free to keep discussing though
