### ISSUE TITLE
I don't get it

### ISSUE THREAD

**Issue by ccorcos** [jedwards1211/meteor-webpack-react#4]
Why use webpack?

**Comment by jedwards1211** [comment]
There's a good list of reasons in the readme.  If none of those reasons
appealed to you, then I guess no need to worry about it


On Mon, Jul 27, 2015, at 01:06 PM, Chet Corcos wrote:
> Why use webpack?


> — Reply to this email directly or view it on GitHub[1].


>



Links:

  1. https://github.com/jedwards1211/meteor-webpack-react/issues/4

**Comment by ccorcos** [comment]
Well its just another build system right? I like to ES6 module imports stuff for controlling load order. But I'm not sure how this plays with the rest of the meteor ecosystem. Is this just a little side project, or is this meant for serious development?

**Comment by AdamBrodzinski** [comment]
@ccorcos I think one of the big draws is using things like hot-reloading on a per module/function basis:

https://github.com/gaearon/react-hot-loader
https://vimeo.com/100010922

- es6 module support today (without .import filename hacks), 
- partial loading of javascript files (in a large app just load feed js and then when going to profiles load profiles page js/css.
- splitting up files instead of one large meteor js file

I think it's mainly useful for large apps that have specific needs.

I haven't used it yet outside of a few tests so i'm not sure what conflicts may popup with Meteor.

At any rate it sounds pretty cool :+1: I wish Meteor would/could use webpack for their packaging!

**Comment by jedwards1211** [comment]
I'm using it for serious development.  Webpack plays very well with the
React ecosystem...Meteor doesn't play so well with the React ecosystem.
To me using the two together is more acceptable than using the standard
Meteor React tools.


On Tue, Jul 28, 2015, at 01:47 AM, Chet Corcos wrote:
> Well its just another build system right? I like to ES6 module imports
> stuff for controlling load order. But I'm not sure how this plays with
> the rest of the meteor ecosystem. Is this just a little side project,
> or is this meant for serious development?


> — Reply to this email directly or view it on GitHub[1].


>



Links:

  1. https://github.com/jedwards1211/meteor-webpack-react/issues/4#issuecomment-125469904

**Comment by ccorcos** [comment]
Wow, that hot-reloater is sweet! Much faster than recompiling all the files and refreshing.

Meteor needs to get on it with their build tools. They need something that works with common.js, but I'm not sure they're ever going to do that.

With this package, do I lose any Meteor features? Can I deploy an application and live-reload the app?

**Comment by grigio** [comment]
@ccorcos currently it doesn't seem this approch break something #1 . If you change something in the client webpack reloads, if you change on the server meteor reloads

**Comment by ccorcos** [comment]
I see. Does webpack also work for Node? Or is it just a browser thing?

**Comment by AdamBrodzinski** [comment]
> I see. Does webpack also work for Node? Or is it just a browser thing?

I don't have any experience with this but it seems like yes? 
 http://jlongster.com/Backend-Apps-with-Webpack--Part-I

**Comment by ccorcos** [comment]
Oy vey. My eyes start to gloss over as soon as I start thinking about spending that much time on a build system before I can even start coding an isomorphic web app with all the bells and whistles I want.

**Comment by jedwards1211** [comment]
Unless anyone has any objections I'll close this issue

**Comment by AdamBrodzinski** [comment]
:+1:  Sounds good to me. If I have some time this week I can work on drafting up another readme and perhaps we can cherry pick some things out of it if it ends up being easier to glance at and understand.
