### ISSUE TITLE
Source maps broken since "redbox-react"

### ISSUE THREAD

**Issue by jbbr** [jedwards1211/meteor-webpack-react#40]
Since commit ecc75187892a97e464bf8464b817145e64606d11 source maps seems to be broken

The nice big red error stacktrace is shown but every class name gets "ProxyClass", line numbers are wrong and the Chrome inspector does only show the bundled file names.

![screen_after](https://cloud.githubusercontent.com/assets/682607/9829222/f1f46dde-58fb-11e5-9915-b131290fdf3f.jpg)

With the previous commit 9e6a666f66a0fb1e4b1015b596c78ead4180b170 the big red error stacktrace is gone but Chrome shows correct filenames and line numbers (I intentionally broke App.jsx on line 27)

![screen_before](https://cloud.githubusercontent.com/assets/682607/9829233/4965a89e-58fc-11e5-9cb4-f9243d2cc161.jpg)

**Comment by AdamBrodzinski** [comment]
Hmmm that's weird. I wonder if changing devTool source maps to `'source-maps'` [here](https://github.com/jedwards1211/meteor-webpack-react/blob/9e6a666f66a0fb1e4b1015b596c78ead4180b170/webpack/webpack.config.client.dev.js#L10). I'll try to look into this over the weekend.

It looks like redbox has a few issues on their repo, [delicate-error-reporter](https://github.com/aulizko/delicate-error-reporter) might be a bit more stable?

**Comment by jbbr** [comment]
Wow, fast answer :)
I've tried both of your suggestions:

"source-maps" and "eval" in "devtool" setting didn't change anything but maybe there was still some cached sourcemap active or something like that.

delicate-error-reporter looks nice but the stack trace and inspector log does look the same as with redbox

**Comment by AdamBrodzinski** [comment]
No prob :smile:

I thought I remember that some of the babel transforms work by wrapping classes... i'm wondering if all the error reporters do this? I guess they would have to wrap everything with a try/catch or something to snatch up the errors.

At any rate I think if you remove the 2nd item in the react-transform array that should take it back to normal.

```
    // removing this:
     {
        "target": "react-transform-catch-errors",
        // the second import is the React component to render error
        // (it can be a local path too, like "./src/ErrorReporter")
        "imports": ["react", "redbox-react"]
      }
```

**Comment by AdamBrodzinski** [comment]
Ok now i'm more confused.... I fired up my fork of webpack (commit ecc7518) and it's working for me. Perhaps it's some kind of caching issue? I know i've seen what you've mentioned though.

Here's what I have with a debugger and showing a 'paused on caught exception' showing vim line number and sourcemap:
![screen shot 2015-09-11 at 10 00 42 pm](https://cloud.githubusercontent.com/assets/1445367/9829406/a14ebafe-58d0-11e5-9037-c0e60fe91b4d.png)

**Comment by jedwards1211** [comment]
Yeah, this caught me off guard too.  `ProxyClass` is obviously from `react-redbox`, hence the `tryRender` method...but I'm not sure what to think yet.  I haven't seen this issue in my projects yet...

**Comment by jedwards1211** [comment]
Okay, I was able to reproduce in the latest version of this poject, with `source-map` also...

**Comment by jedwards1211** [comment]
Without `react-redbox` and `source-map`, I was able to put breakpoints in `App.jsx`.  I wonder if `react-redbox` messes up the source maps?

**Comment by AdamBrodzinski** [comment]
Yea this is breaking for me too... I thought it was a problem with the debugger lines... I need some sleep :laughing:

**Comment by gaearon** [comment]
Oh wait, are you all folks using `React.createClass()` :-) ?

Then you'll need to put [`react-display-name`](https://www.npmjs.com/package/babel-plugin-react-display-name) Babel plugin before `babel-plugin-react-transform` as [shown here](https://github.com/gaearon/babel-plugin-react-transform/pull/20/files). Sorry it wasn't in the docs!

**Comment by gaearon** [comment]
Or wait, I'm missing the point again. The issue is about filenames, not about `ProxyClass`. Or is about both? These are unrelated issues. You can fix `ProxyClass` by `babel-react-display-name` as I wrote in the previous comment, but this is unrelated to sourcemaps.

**Comment by jedwards1211** [comment]
Ah, cool, thanks @gaearon!  I'll close my issue once I've verified that fixes it.  Yes, we're still in the dark ages here :) I haven't investigated a way to use the `MeteorDataMixin` with `React.Component` classes yet.

**Comment by jedwards1211** [comment]
@gaearon I've spent the past hour or two investigating the source map issue, and I'm still not sure what it is.  I can't repro by altering `react-transform-boilerplate` yet.  I'm using `webpack-dev-server` instead of a custom `server.js` with webpack middleware, so maybe that's the problem.

**Comment by gaearon** [comment]
Let me take a look too.

**Comment by gaearon** [comment]
What do you folks run? `npm run dev`? `npm run dev-debug`?

**Comment by jedwards1211** [comment]
@gaearon wow, thanks.  In this project just `./dev` in the root directory.

**Comment by jedwards1211** [comment]
I put up a simplified project here: https://github.com/jedwards1211/react-transform-source-map-test

In that project stack traces inside component `render()`s are affected

**Comment by jedwards1211** [comment]
Actually hang on, let me remove some unnecessary deps from that

**Comment by gaearon** [comment]
>Note that the stack trace printed from within App.render links to the Webpack bundle, but stack traces in other locations link to the pre-transpiled source.

What is the _expected_ behavior? I don't fully understand the issue so showing expected / actual behavior would help.

**Comment by gaearon** [comment]
From your initial post screenshot, it doesn't seem that *sourcemaps* are broken. It just says `development.js` instead of `App.js` because that's where the error was unhandled. Because `react-transform-catch-errors` caught the original error from `App.js`. I'm not actually sure there's anything we can do to influence this, but let me take another look..

**Comment by jedwards1211** [comment]
Ah, sorry.  In `react-transform-source-map-test`, the unexpected stack trace is:

```
Error: test inside App.render()
    at App.render (eval at <anonymous> (http://localhost:3000/static/bundle.js:1543:2), <anonymous>:58:21)
    at App.proxiedMethod (eval at <anonymous> (http://localhost:3000/static/bundle.js:1585:2), <anonymous>:44:30)
    at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (eval at <anonymous> (http://localhost:3000/static/bundle.js:1105:2), <anonymous>:789:34)
    at ReactCompositeComponentMixin._renderValidatedComponent (eval at <anonymous> (http://localhost:3000/static/bundle.js:1105:2), <anonymous>:816:14)
    at ReactPerf.measure.wrapper (eval at <anonymous> (http://localhost:3000/static/bundle.js:769:2), <anonymous>:70:21)
    at ReactCompositeComponentMixin.mountComponent (eval at <anonymous> (http://localhost:3000/static/bundle.js:1105:2), <anonymous>:237:30)
    at ReactPerf.measure.wrapper [as mountComponent] (eval at <anonymous> (http://localhost:3000/static/bundle.js:769:2), <anonymous>:70:21)
    at Object.ReactReconciler.mountComponent (eval at <anonymous> (http://localhost:3000/static/bundle.js:775:2), <anonymous>:38:35)
    at mountComponentIntoNode (eval at <anonymous> (http://localhost:3000/static/bundle.js:1003:2), <anonymous>:248:32)
    at ReactReconcileTransaction.Mixin.perform (eval at <anonymous> (http://localhost:3000/static/bundle.js:817:2), <anonymous>:134:20)
```

Expected stack trace as correctly prints when I throw an error from App in `react-transform-boilerplate`:
```
Error: test
    at App.render (App.js:32)
    at App.proxiedMethod (createPrototypeProxy.js:44)
    at App.tryRender (development.js:32)
    at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:789)
    at ReactCompositeComponentMixin._renderValidatedComponent (ReactCompositeComponent.js:816)
    at ReactPerf.measure.wrapper (ReactPerf.js:70)
    at ReactCompositeComponentMixin.mountComponent (ReactCompositeComponent.js:237)
    at ReactPerf.measure.wrapper [as mountComponent] (ReactPerf.js:70)
    at Object.ReactReconciler.mountComponent (ReactReconciler.js:38)
    at mountComponentIntoNode (ReactMount.js:248)
```

**Comment by jedwards1211** [comment]
I can't tell if source maps are broken or something else about my webpack configuration is wrong.

**Comment by gaearon** [comment]
OK, I think I understand the problem now. You used to have nice filenames the console, but now you see `eval at <anonymous> (...)`. Is this correct?

**Comment by jedwards1211** [comment]
Right.  In any case now that I've seen everything works with `react-transform-boilerplate`, seems doubtful it's an issue with any of your code

**Comment by gaearon** [comment]
Maybe it was https://github.com/jedwards1211/meteor-webpack-react/commit/4b0bd6bc2f6d6f9a43edaf2d483988f6ef3525d0 that introduced the change?

**Comment by jedwards1211** [comment]
I've tried with various devtool options, in `react-transform-boilerplate` as well, no fundamental difference in the behavior of either project

**Comment by jedwards1211** [comment]
quite the complex mash of tools here, and I don't know enough to have a good idea what's causing this

**Comment by jedwards1211** [comment]
Specifically `eval` and `source-map` both work in `react-transform-boilerplate` and not in my `react-transform-source-map-test`

**Comment by gaearon** [comment]
Sure, no worries. I know it's a crazy mix. Looking into your test case—thanks for assembling it.

**Comment by jedwards1211** [comment]
And the weird thing to me is that in these broken projects source maps are present and work for breakpoints most of the time, just not for stack traces from inside a `render()`.  It's oddly specific

**Comment by gaearon** [comment]
In the project that you created, there is no `react-transform-catch-errors`. Is this on purpose?

**Comment by jedwards1211** [comment]
Yes, just to make sure that it's not related to this issue

**Comment by gaearon** [comment]
Just to clarify.. Do I see the same thing you see?

<img width="688" alt="screen shot 2015-09-15 at 01 45 41" src="https://cloud.githubusercontent.com/assets/810438/9863763/7faafb24-5b4b-11e5-9333-f93809ce3f61.png">

**Comment by jedwards1211** [comment]
Good call, because surprisingly that's different from what I see.  I'm using Node v0.10.36, NPM v1.4.28...

**Comment by gaearon** [comment]
I'm on io.js 2. Let me try 0.10.

**Comment by jedwards1211** [comment]
Here's my screenshot:

![image](https://cloud.githubusercontent.com/assets/1448194/9863788/c8552aae-5b08-11e5-9730-47f1c7cce516.png)

**Comment by gaearon** [comment]
In your case are long `webpack://` URLs the problem? Are they not clickable? I still don't see which exactly issue you are referring to :-(

**Comment by jedwards1211** [comment]
Sorry I haven't done a great job of explaining it.  The `webpack://` URLs are clickable but they go to the transpiled bundle, rather than the pre-transpiled code.  In `react-transform-boilerplate` the pretty file links go to the pre-transpiled code

**Comment by jedwards1211** [comment]
Okay, I got the same console output when running with Node v0.12.7.  I haven't tried io.js yet, let me install it...

**Comment by gaearon** [comment]
OK, I understand it now. :-)

I don't get this behavior even on Node 0.10.
Clicking both `App.jsx` and `index.jsx` in all three stack traces brings me to those files respectively.

<img width="515" alt="screen shot 2015-09-15 at 01 54 29" src="https://cloud.githubusercontent.com/assets/810438/9863875/baab15d2-5b4c-11e5-9035-97292b113423.png">

**Comment by jedwards1211** [comment]
Wait a minute, I was thrown off by the fact that `eval` source maps are partially transpiled.  Let me check with `source-map` again.

**Comment by gaearon** [comment]
(Note that I ran your example as is, without changing the config.)

**Comment by jedwards1211** [comment]
Aha, so with `source-map`, Node v0.12.7, here's my console output.  This one is clearly a link to the entire bundle instead of just `App.jsx`

![image](https://cloud.githubusercontent.com/assets/1448194/9863914/f62afd9a-5b09-11e5-9b43-314ea3a38a7f.png)

**Comment by jedwards1211** [comment]
This is quite the rabbit hole.  What other differences in our systems do you think would be worth checking?  Maybe the difference could lie in our browsers, even?

**Comment by jedwards1211** [comment]
I'm on Chrome Version 44.0.2403.155 (64-bit)

**Comment by gaearon** [comment]
Let's start by sticking to Node 0.10 and your default project settings.
I'm on Chrome 45.0.2454.85 (64-bit).

**Comment by jedwards1211** [comment]
okay, I'll update Chrome...

**Comment by gaearon** [comment]
Do I understand correctly that removing plugins from `.babelrc` and making it

```js
{
  "stage": 0
}
```

fixes the problem for you?

**Comment by jedwards1211** [comment]
Oh, man, I'm so sorry, I forgot to check that.  It actually doesn't fix the problem.  I thought for sure it had to do with `react-transform` since it's wrapping the class.  Well, obviously it's something else so I'm sorry for wasting your time.  Thanks for your help though

**Comment by gaearon** [comment]
Not a problem for me, let's keep looking. Please post your exact `webpack`, `webpack-dev-server` and `webpack/~/webpack-core/~/source-map` versions?

**Comment by gaearon** [comment]
You can try copying `babel*` and `webpack*` folders from `react-transform-boilerplate` if it works for you. If it fixes the problem then you have a bad version of something in the test project.

**Comment by jedwards1211** [comment]
```
andy@hexagon-sun:~/react-transform-issue$ npm ls webpack
react-transform-source-map-test@0.0.1 /home/andy/react-transform-issue
└── webpack@1.12.1 

andy@hexagon-sun:~/react-transform-issue$ npm ls webpack-dev-server
react-transform-source-map-test@0.0.1 /home/andy/react-transform-issue
└── webpack-dev-server@1.10.1  extraneous
```

And `source-map` is `0.4.4`.

**Comment by jedwards1211** [comment]
Copied the entire `node_modules` over from `react-transform-boilerplate`, still no change

**Comment by gaearon** [comment]
Do you have this problem when using https://github.com/gaearon/react-hot-boilerplate?

**Comment by jedwards1211** [comment]
@gaearon I finally figured it out by transforming `react-transform-boilerplate` step by step into my project.  There are two unrelated causes for the issue (either one can cause the issue by itself):
* using `devtool: 'eval-source-map'`
* I accidentally left out `.stack` in `console.error(new Error('test inside App.render()'))`

So in other words when I changed to `devtool: 'source-map'` or `devtool: 'eval'` and added `.stack` to that line, it fixed the problem.

Thanks for your help again, and I hope you didn't have to sacrifice too much time on this.  And thanks for all you've done for the React community!

**Comment by gaearon** [comment]
No problem. Every riddle feels impossible to solve until it's solved and feels obvious in retrospect.
:-)

**Comment by jedwards1211** [comment]
@gaearon aha, try this in `react-transform-boilerplate`:
* `devtool: 'source-map'` in `react-transform-boilerplate`
* `App.js`:
```
export class App extends Component {
  render() {
    console.error(new Error('test').stack);
    throw new Error('test');
    ...
```
With these settings redbox displays the bad (i.e. linking to the bundle) stack trace, even though the one printed by `console.error` is good:
![image](https://cloud.githubusercontent.com/assets/1448194/9864935/c85a205c-5b14-11e5-909b-ce7e590e7747.png)

**Comment by jedwards1211** [comment]
@gaearon Yup, although it won't be obvious to me until if/when I know how the various `devtool` options work on a deep enough level to understand why they have these effects.

**Comment by gaearon** [comment]
@jedwards1211 `redbox-react` [just uses](https://github.com/KeywordBrain/redbox-react/blob/79e674daa06998954729e85cde96d14a383cc11e/src/index.js#L12) [error-stack-parser](https://github.com/stacktracejs/error-stack-parser), must be their issue?

**Comment by jedwards1211** [comment]
Yeah, I'll go read their source

**Comment by jedwards1211** [comment]
So they parse `error.stack` as well...I think `console.error(error.stack)` must work some magic (resolve the source maps)

**Comment by gaearon** [comment]
Definitely possible. However it isn't hard for us to provide filename info to the error reporter. Would you like to make a PR to `react-transform-catch-errors` to pass `filename` to `<ErrorReporter>`? It already should receive `filename` in `options`.

**Comment by jedwards1211** [comment]
Sure, let me take a look

**Comment by jedwards1211** [comment]
Or would you prefer passing all properties except `components`, `imports`, and `locals`?

**Comment by gaearon** [comment]
I think just `filename` is fine; arbitrary options from config aren't being passed anyway right now.

**Comment by jedwards1211** [comment]
i.e.
```
let {components, imports, locals, ...props} = this.props;
props.error = err;
return React.createElement(ErrorReporter, props);
```

**Comment by jedwards1211** [comment]
okay, sounds good

**Comment by jedwards1211** [comment]
Just fyi: https://github.com/novocaine/sourcemapped-stacktrace

**Comment by gaearon** [comment]
Doing this in plugin is better because we _know_ filename there—we don't have to guess, and `devtool` doesn't matter.

**Comment by jedwards1211** [comment]
Right, I'm just thinking about the fact that it won't work for the entire stack trace, just the deepest module.  In any case it would be nontrivial to use that package right now, and it only supports chrome at the moment

**Comment by jedwards1211** [comment]
@jbbr @AdamBrodzinski I just changed the `devtool` to `eval` and pushed.  Feel free to use `eval-source-map` in your own work, but note that this issue will rear its head if you do.

**Comment by AdamBrodzinski** [comment]
@jedwards1211 Ah thanks for the heads up! What a crazy bug! I'm using eval currently anyway since it seems to be the fastest reloads. Thanks!!

**Comment by jbbr** [comment]
Thanks for debugging this issue.
Though for me using `eval-source-map` without redbox-react is still the better choice, as I get correct line numbers for my original files and hot reload is still fast (much faster as with `source-map`).

`eval` + `redbox-react` prints wrong line numbers for me - but at least filenames are correct now :+1:

**Comment by jedwards1211** [comment]
@jbbr I understand -- for the default in this skeleton I just want to use the config that's least likely to make people open new issues.
