### ISSUE TITLE
Missing NPM dependencies

### ISSUE THREAD

**Issue by orlade** [jedwards1211/meteor-webpack-react#41]
I just set up the `simple-todos` branch and after running `npm install` and `./dev` as instructed, I discovered I still had a lot of missing dependencies to install. I don't know if this is expected, but it wasn't mentioned in the README. In any case, the errors went away after I installed the following:

```
ast-types connect-history-api-fallback css-selector-tokenizer cssnano express http-proxy lazy-cache loader-utils minimist normalize-selector optimist postcss postcss-modules-extract-imports postcss-modules-local-by-default postcss-modules-scope regenerate regjsgen regjsparser serve-index socket.io socket.io-client stream-cache strip-ansi supports-color uniqs webpack-dev-middleware wordwrap
```

Is this just me having something configured wrong, or should these be in `package.json` somewhere?

I also got `./dev: line 20: /home/oliver/meteor-webpack-react/node_modules/webpack/bin/webpack.js: Permission denied` which may be a separate issue, but may be related?

**Comment by orlade** [comment]
So I tried again with `nvm` running `npm` v2.11.3 and `node` v0.12.7 and it installed and ran with no problems. My system defaults to `node` v0.10.25 and `npm` v2.7.0 which was when I had the problems. Perhaps you could say something about minimum requirements in the README?

**Comment by AdamBrodzinski** [comment]
Oh wow, hmmm. It should work with just an `npm install` and then `./dev` . Did you have to install those globally? I think the todos branch might be out of date. Did the master do this as well?

btw, i'm running node 0.10.36  and npm 1.4.28 (actually I just upgraded it appears i'm *way* out of day lol).

re-installing a fresh repo with node 10.36 (via NVM) and npm  2.14.3  on OSX 10.10 I was able to build with no errors (some peerDep warnings).

> ./dev: line 20: /home/oliver/meteor-webpack-react/node_modules/webpack/bin/webpack.js: Permission denied

You can try `chmod 777 dev` to up the permissions on the script.

Here's a video tutorial I made getting it going: https://www.youtube.com/watch?v=QpixFzvf8U8

**Comment by orlade** [comment]
Yeah, most likely it was just my environment. I installed a couple of them locally, ran `./dev` and saw a couple of new errors, so installed a couple more, and so on. I'm not sure I tried on master in the end, but I'll give a closer look next week.

The video makes it look so easy. Consider this not an open issue. :+1:
