### ISSUE TITLE
webpack can't find jquery

### ISSUE THREAD

**Issue by gdub01** [jedwards1211/meteor-webpack-react#46]
Working with http://wysiwygjs.github.io/ via npm https://www.npmjs.com/package/wysiwyg.js

I'm requiring it into a react component like:

require('wysiwyg.js/src/wysiwyg-editor.js');

The file I want requires jQuery to do its thing but it can't find jQuery 

./~/wysiwyg.js/src/wysiwyg-editor.js
Module not found: Error: Cannot resolve module 'jquery' in /websites/webpack-blog/node_modules/wysiwyg.js/src
resolve module jquery in /websites/webpack-blog/node_modules/wysiwyg.js/src

I think it's because meteor, not webpack imports it?

**Comment by AdamBrodzinski** [comment]
Yea it's pulling it in [on this line](https://github.com/wysiwygjs/wysiwyg.js/blob/master/src/wysiwyg-editor.js#L8).

I *think* what you need to to tell webpack that jQuery is already available globally and to resolve any 'jquery' calls to the global `$`.

I haven't had to do this yet but I would try out externals: http://webpack.github.io/docs/library-and-externals.html

```
//webpack.config.client.js

...

externals: {
  // require("jquery") is external and available
  //  on the global var jQuery
  "jquery": "jQuery"
},

...
```

Or it could even be this: http://webpack.github.io/docs/shimming-modules.html#plugin-provideplugin

**Comment by gdub01** [comment]
I copied and pasted your code exactly  to

webpack.config.client.js

...

externals: {
  // require("jquery") is external and available
  //  on the global var jQuery
  "jquery": "jQuery"
},

...
and that worked... thanks a lot!
