### ISSUE TITLE
Webpage is not available

### ISSUE THREAD

**Issue by designeng** [jedwards1211/meteor-webpack-react#48]
After `npm install` and `./dev` there's redirect to `http://0.0.0.0:3000/index.html` and no page available. Last message from terminal: "webpack: bundle is now VALID". What is wrong?

**Comment by jedwards1211** [comment]
As it says in the readme, "Make sure to wait for Meteor to say it's listening", which can happen after Webpack says that.  Did Meteor never print anything after that?  How long did you wait?

**Comment by designeng** [comment]
About 5 minutes, is not it enough :) ? No message

**Comment by AdamBrodzinski** [comment]
Hmm that's odd. It shouldn't redirect to index.html... what happens if you just enter: `http://localhost:3000/` into th ebrowser? Same thing?

You could try checking out previous commits to see if that helps. :frowning:

**Comment by jedwards1211** [comment]
Oh yeah, it definitely shouldn't take that long.  I'm not sure if `0.0.0.0` works on all browsers/systems.  Another thing to try would be to manually run the webpack commands in two terminals, then once they finish loading, in a third terminal manually run the meteor command from the `./dev` script.  That way you could at least see Meteor showing its progress in the console.

**Comment by jedwards1211** [comment]
@designeng any update on this?  Recently when trying some experimental Webpack config, Meteor never seemed to finish loading, but I haven't figured out why.
