### ISSUE TITLE
Great Package - Can you make an example of

### ISSUE THREAD

**Issue by reduxdj** [jedwards1211/meteor-webpack-react#5]
"or if you want to use Sass, you can require the Sass files"?

Specifically, I am using Stylus and also CJSX (coffeescript). I'd like to do the what you say is possible, I Just need an example please

**Comment by jedwards1211** [comment]
Sure!  You would just need to `npm install --save-dev stylus-loader coffee-loader` and add them to your Webpack config, like this (copied from their websites):

```
module: {
  loaders: [
    {
      test: /\.styl$/,
      loader: 'css-loader!stylus-loader?paths=node_modules/bootstrap-stylus/stylus/'
    },
    { test: /\.coffee$/, loader: "coffee-loader" },
    { test: /\.(coffee\.md|litcoffee)$/, loader: "coffee-loader?literate" }
  ]
}
```

Then in your code (I don't know much CoffeeScript):
```
require './somestyle.styl'
caffeineRush = require './strong.coffee'
```

**Comment by jedwards1211** [comment]
I'm closing this out, if you have any more questions about this, feel free to PM me!

**Comment by outluch** [comment]
Hi! I love coffee, so i made a fork with some demo cjsx and configuration for hot module replacement. A bit hacky but works. https://github.com/outluch/meteor-webpack-react-cjsx
