### ISSUE TITLE
node-inspector not running

### ISSUE THREAD

**Issue by rralian** [jedwards1211/meteor-webpack-react#52]
When I run the app using `./debug` I get the message:
```bash
Node Inspector v0.12.3
Visit http://127.0.0.1:8080/?ws=127.0.0.1:8080&port=5858 to start debugging.
```
But that never actually works. I have node-inspector installed globally. For some reason it doesn't work for me with just `meteor debug` in _any_ meteor project, but I am able to get it running in other meteor projects via `meteor --debug-port 5000`.

So I tried modifying [this line](https://github.com/jedwards1211/meteor-webpack-react/blob/master/debug#L32) to read:
```js
meteor --debug-port 5000 --settings ../settings/devel.json &
```
And then node-inspector does start working for me. I don't know if others are running into problems with `./debug` or if this is specific to my system, but figured I'd report it and my local fix.

**Comment by jedwards1211** [comment]
Hmmm, would you mind trying with Node Inspector v0.10.36?  I know Meteor isn't supposed to be compatible with much later versions of node inspector, though I don't know if it would cause this issue.  In any case, I've been using v0.10.36 and I haven't seen this problem with `./debug` or `meteor debug` in any other projects.

**Comment by jedwards1211** [comment]
Any update on this?
