### ISSUE TITLE
Environment variables 

### ISSUE THREAD

**Issue by tomitrescak** [jedwards1211/meteor-webpack-react#57]
Hi, I've found out that using this solution no environemnt variables are set (e.g. process.env.PWD), so I tries to set them manually. For some reason the process.env stays empty ;/

I've found out, that you can somehow set variables in `../settings/devel.json` but these are not contained in processs.env. Where are these properties set?

Thanks!

**Comment by AdamBrodzinski** [comment]
I think this is because using `export` will only change them in your terminal, not the process that the script is running. You would have to put them into a `env.sh` file and then `source env.sh` in the script before the last `meteor` command runs.

In retrospect the `settings` folder should prob have folder to make this easier to store, this way it plays nicely with MUPs assumption of settings.json.However MUP still requires env variables to be manually put in the mup config.
```
settings
├── devel
│   ├── env.sh
│   └── settings.json
├── stage
│   ├── env.sh
│   └── settings.json
├── prod
│   ├── env.sh
│   └── settings.json
```

**Comment by tomitrescak** [comment]
I'm not sure if that's the case, I tried to modify it [here](https://github.com/jedwards1211/meteor-webpack-react/blob/master/dev#L32) as `FOO=foo meteor --settings ../settings/devel.json &` but the FOO variable was not avaialable in the process.env stack. But I'll try the soource approach.

That means to modify dev.sh as following?

```
cd $METEOR_DIR
ln -sf $WEBPACK_DIR/$SERVER_BUNDLE server/server.bundle.js &&
ln -sf $WEBPACK_DIR/loadClientBundle.html client/loadClientBundle.html &&
source $SCRIPTPATH/settings/prod/env.sh &&
meteor --settings ../settings/devel.json &
```

Actually I tried something similar

```
cd $METEOR_DIR
ln -sf $WEBPACK_DIR/$SERVER_BUNDLE server/server.bundle.js &&
ln -sf $WEBPACK_DIR/loadClientBundle.html client/loadClientBundle.html &&
export FOO=bar &&
meteor --settings ../settings/devel.json &
```

But again, no luck.
I need this to control Velocity framework and set some paths in development and production.

Sorry to annoy this much, but am not th best in shell programming.

**Comment by tomitrescak** [comment]
Hi, I tried it all and variables still do not make it to meteor process. I even found the foillowing plugin in dev:

```
  new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify('production'),
      }
    }),
```

So I tried setting varibales through there and no luck.

**Comment by jedwards1211** [comment]
@tomitrescak Do you mean you found the plugin in prod?  I just double-checked, it's not in dev, was never supposed to be.

And let me confirm, you're trying to access `process.env.PWD` on the server, right?  Is `process.env` defined?  I think Meteor stomps on `require` and similar things because isobuild packages the resulting code into a different place than the source files.

Also, as far as I can tell, the `meteor` command actually runs the server in a separate process...`meteor` is just the build/monitor process, and when it says 'Meteor server restarted', that means it literally restarted the server process.  That's probably why even exported variables fail to make it into your server; they would only get into the `meteor` process.  I've found it quite frustrating at times, though I haven't looked into controlling how the server process gets run...

It's definitely unlikely that `DefinePlugin` is causing the problem as that's a simple text substitution plugin.

You might be encountering problems because if you use this:
```
'process.env': {
  NODE_ENV: 'production'
}
```
Then `if ('production' === processs.env.NODE_ENV)` gets transformed to `if ('production' === production)`.  You have to use `JSON.stringify` to make it substitute with a string literal:

```
'process.env': {
  NODE_ENV: JSON.stringify('production')
}
```

It's quite standard practice to use the define plugin for `NODE_ENV`, because it allows UglifyJS to remove if blocks that get transformed to `if ("production" === "production") {` etc.  Another common practice is not to hard code `'production'` in there and do
```
'process.env': {
  NODE_ENV: JSON.stringify(process.env.NODE_ENV),
}
```
But the prod webpack configs are really only meant for prod anyway.

**Comment by tomitrescak** [comment]
OK. For most parts I can make the settings come from the database (like setting the upload directory).

But, for example I need to control the Velocity testing via Environment variables. What is your take on how to approach this?

For example, with Jasmine you can control which part of testing you want to execute, where to pipe the logs and so on. With no environment variables (yes, they come as empty "process.env id {}") this is quite difficult. 

Thanks!

**Comment by tomitrescak** [comment]
Guys, the problem is even bigger than I expected. I managed to solve almost everything (by not using environment variables), but there are several places where those variables are needed and it's quite limiting. 

1. It is not possible to send emails. Even when I set the MAIL_URL such as `process.env.MAIL_URL = smtp://${config.email.server};` and before sending mail I check if that environment variable is set, Meteor keeps complaining that `(Mail not sent; to enable sending, set the MAIL_URL environment variable.)` I do not know if that is because it is running in a different process or not, but it does not recognise these variables.

2. Velocity, such as Sanjo's jasmine package is not possible to control as it also does not recognise the environment variables I set.

Here is an example code:

```
process.env.MAIL_URL = `smtp://${config.email.server}`; 

Email.send(...) // this will fail ;(
```

**Comment by tomitrescak** [comment]
I have debugged the server and it is clear that in my server method the MAIL_URL is defined, but when I call Email.send in that context it does not exist. Really weird.

**Comment by tomitrescak** [comment]
OK. I'm starting to wrap my head around this problem.
The issue is that Meteor runs in a different process then Webpack server. Therefore setting environment variables for meteor does not affect variables in my code and vice versa.

So, modifying the startup parameters in the `dev` script such as `MAIL_URL=smtp://godspaw:Bailen50@smtp.gmail.com:465 meteor --settings ../settings/devel.json &` allowed me to send emails.

The problem is, that that code that is running in webpack server does not have access to meteor environment variables.

I'm not sure if there is a solution for this ;(

**Comment by AdamBrodzinski** [comment]
@tomitrescak

Interesting.... so the easiest work around i've come up with is to fallback to `meteor_core` and call
 `ENVS = process.env;` in a server file. Then in webpack I can access `ENV.FOO` from webpack (or anywhere). I tend to use Meteor settings instead of env vars but sometimes there's no option.

Also if you have a lot of vars you cold comment out the part that automatically starts up meteor and then manually start it up after waiting for webpack to boot. That way you could even use a makefile with env variables so you don't have to manually set them each time.

**Comment by jedwards1211** [comment]
@tomitrescak the webpack process is different, but all it does is build the server bundle, which then gets loaded and run by the Meteor server process, so they should have access to the exact same things unless webpack hides them for some reason.  But i'm more inclined to believe that Meteor hides them...let me do a little digging...

**Comment by jedwards1211** [comment]
this suggests it should be possible: http://www.meteorpedia.com/read/Environment_Variables
I'll see if I have any trouble on my machine...

**Comment by jedwards1211** [comment]
Aha, I think we need `target: 'node'` in `webpack.config.server.js`

**Comment by jedwards1211** [comment]
@tomitrescak yup, all that was needed is `target: 'node'` in the webpack config.  I just pushed it.  This should be fixed, let me know if you have any problems and I'll reopen.  I was wrong to suspect Meteor in this case!

**Comment by jedwards1211** [comment]
Well shoot, using `target: 'node'` means that if you `require('events')` it won't get transformed into `__webpack_require__('events')` meaning if will break if you're running in Meteor.  Excuse my french but I just have to say **fuck Meteor/isobuild for taking away `require`**, it makes everything, everything, everything difficult and really pisses me off.  Let me see if I can figure out a workaround.

**Comment by jedwards1211** [comment]
Okay, I found a better workaround in the webpack config: `node: { process: false }`.  With this it should be possible to require the usual node stuff, but `process.env` is present.  Pushed again.  Let me know how that works

**Comment by jedwards1211** [comment]
@tomitrescak I found an even better workaround using `target: 'node'` and `plugins: [ new webpack.BannerPlugin('var require = Npm.require;\n', {raw: true}), ... ]`.

I'm pleased to announce that thanks to this research, I also figured out how to enable source maps on the server!  Thanks also to https://github.com/evanw/node-source-map-support.  Just pushed -- check it out!

**Comment by wuxianliang** [comment]
I am trying the new codes. When I set intuitively 
```json
{
  "public": {
    "env": "DEVEL",
    "MONGO_URL": "mongodb://127.0.0.1:27017/jt"
  },
  "secret": "golf1234"
}
``` 
in devel.json, it does not work. 
But adding
```
export  MONGO_URL=mongodb://127.0.0.1:27017/jt && meteor ....
```
to dev works.

**Comment by tomitrescak** [comment]
This is still not working. In devel I get following when outputtting process.env:

```
"TERM_PROGRAM":"iTerm.app","SHELL":"/bin/bash","TERM":"xterm-256color","CLICOLOR":"1","TMPDIR":"/var/folders/y6/ylphsy7j34lgkbc47nqcwlxh0000gn/T/","Apple_PubSub_Socket_Render":"/private/tmp/com.apple.launchd.p1QkeaquNU/Render","OLDPWD":"/Users/tomi/.meteor/packages/meteor-tool/1.1.9/mt-os.osx.x86_64","USER":"tomi","COMMAND_MODE":"unix2003","SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.jVIFPfuDWO/Listeners","__CF_USER_TEXT_ENCODING":"0x1F5:0x0:0x0","LSCOLORS":"GxFxCxDxBxegedabagaced","PATH":"/opt/local/bin:/opt/local/sbin:/Users/tomi/.dnx/runtimes/dnx-mono.1.0.0-beta5/bin:/Users/tomi/.dnx/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin","MONO_MANAGED_WATCHER":"disabled","DESTINATION":"/var/folders/y6/ylphsy7j34lgkbc47nqcwlxh0000gn/T/iTerm 2.1.3 Update","PWD":"/Users/tomi/Documents/Programming/Github/meteor-webpack-react-modified/meteor_core","DBUS_LAUNCHD_SESSION_BUS_SOCKET":"/private/tmp/com.apple.launchd.n4Z18cLaiT/unix_domain_listener","LANG":"en_AU.UTF-8","ITERM_PROFILE":"Default","XPC_FLAGS":"0x0","XPC_SERVICE_NAME":"0","COLORFGBG":"7;0","HOME":"/Users/tomi","SHLVL":"2","ITERM_SESSION_ID":"w0t0p0","LOGNAME":"tomi","SECURITYSESSIONID":"186a7","PORT":"28647","ROOT_URL":"http://localhost:3000/","MONGO_URL":"mongodb://127.0.0.1:3001/meteor","MOBILE_DDP_URL":"http://localhost:3000","MOBILE_ROOT_URL":"http://localhost:3000","MONGO_OPLOG_URL":"mongodb://127.0.0.1:3001/local","METEOR_SETTINGS":"{\n  \"public\": {\n    \"env\": \"DEVEL\",\n    \"foo\": \"bar\"\n  },\n  \"secret\": \"golf1234\"\n}\n","APP_ID":"1kkvpljtq0j5s32te4b","NODE_ENV":"development","HTTP_FORWARDED_COUNT":"1","METEOR_SHELL_DIR":"/Users/tomi/Documents/Programming/Github/meteor-webpack-react-modified/meteor_core/.meteor/local/shell","METEOR_PARENT_PID":"15149","METEOR_PRINT_ON_LISTEN":"true","NODE_PATH":"","MAIL_URL":"smtp://godspaw:Bailen50@smtp.gmail.com:465","UPLOAD_DIR":"/Users/tomi/Documents/Programming/Github/meteor-webpack-react-modified/meteor_core/.uploads"}
```

This is what I get in prod:

```
{"NODE_ENV":"production"}
```

**Comment by jedwards1211** [comment]
Argggh...I'll keep looking into it...I place all the blame for the difficulty of this integration squarely on Meteor

**Comment by tomitrescak** [comment]
This is black magic. Look at the following code:

```
process.env.UPLOAD_DIR = "foo";
console.log(JSON.stringify(process.env));
```

this is the output:

```
I20151006-09:32:53.752(11)? {"NODE_ENV":"production"}
```

Now ... that is ... a classic WTF.

**Comment by tomitrescak** [comment]
Not to mention that in dev it behaves as expected.

**Comment by jedwards1211** [comment]
Wait a minute...it's probably the Webpack config text-replacing `process.env`...

**Comment by jedwards1211** [comment]
Yup, I had foolishly copied or adapted this code from somewhere: 
```
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify('production'),
      },
    }),
```
This replaces all occurrences of `process.env`.  Not sure why people did it this way??

The fix:
```
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify('production'),
    }),
```

Sorry for the trouble!  I'll push this fix in a moment

**Comment by jedwards1211** [comment]
I never really thought about how fragile this is...the following check wouldn't work with this:

```
var env = process.env;
if ('production' === env.NODE_ENV) {
  ...
}
```

I know I've seen `__DEV__` globals in the React source code so maybe they're doing things in a less fragile way now.  I'll investigate later

**Comment by jedwards1211** [comment]
@tomitrescak luckily I realized almost immediately that it was the DefinePlugin usage when I saw your classic WTF :) thanks for posting that

**Comment by jedwards1211** [comment]
And yes, Webpack and Meteor perform plenty of black magic!  Here's how Meteor executes source files:

```js
   // \n is necessary in case final line is a //-comment
    var wrapped = "(function(Npm, Assets){" + code + "\n})";

    // It is safer to use the absolute path when source map is present as
    // different tooling, such as node-inspector, can get confused on relative
    // urls.

    // fileInfo.path is a standard path, convert it to OS path to join with
    // __dirname
    var fileInfoOSPath = files.convertToOSPath(fileInfo.path);
    var absoluteFilePath = path.resolve(__dirname, fileInfoOSPath);

    var scriptPath =
      parsedSourceMaps[absoluteFilePath] ? absoluteFilePath : fileInfoOSPath;
    // The final 'true' is an undocumented argument to runIn[Foo]Context that
    // causes it to print out a descriptive error message on parse error. It's
    // what require() uses to generate its errors.
    var func = require('vm').runInThisContext(wrapped, scriptPath, true);
    func.call(global, Npm, Assets); // Coffeescript
```
