### ISSUE TITLE
Error building project

### ISSUE THREAD

**Issue by tomitrescak** [jedwards1211/meteor-webpack-react#58]
When executing "./prod" it fails during uglification on all ".jsx" file

For example:
ERROR in client.bundle.js from UglifyJs
Unexpected character '`' [../app/lib/i18n/i18n.en.jsx:465,0]

There I used template strings.

**Comment by AdamBrodzinski** [comment]
When you say all, if you comment out the file does another one throw?

**Comment by AdamBrodzinski** [comment]
You might be able to remove the uglify plugin from the prod config.... Meteor is going to minify it anyway unless the minified package is taken out manually.

**Comment by tomitrescak** [comment]
I can confirm that removing uglify in prod helped:

```javascript
// file: webpack.config.client.prod.js
var webpack = require('webpack');
var config = require('./webpack.config.client');
var _ = require('lodash');

var config = module.exports = _.assign(_.cloneDeep(config), {
  plugins: (config.plugins || []).concat([
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify('production'),
      }
    }),
    new webpack.NoErrorsPlugin(),
    new webpack.optimize.DedupePlugin(),
    // new webpack.optimize.UglifyJsPlugin({
    //   compress: { warnings: false }
    // }),
    new webpack.optimize.AggressiveMergingPlugin(),
    new webpack.optimize.OccurenceOrderPlugin(true),
  ]),
});
```

**Comment by tomitrescak** [comment]
Althought I'm puzzeled by this ;/ I am using template strings all around my project, but the only file it reallly minds is where my i18n strings are stored. I tried to move theimport around my project but no success.

I have in my router.tsx two imports

import "./someother" // has template strings and life is good
import "./i18n" // has template strings and life is miserable

Do you have any idea of why uglify and everything else would complain?

**Comment by jedwards1211** [comment]
Huh.  That's odd because all backticks for template strings should be compiled out into ES5 by babel.  Can you copy and paste that line from `i18n.en.jsx`?

**Comment by tomitrescak** [comment]
Here it goes

```
mf["languages"].en = {
  "activity": "Activity",
  "add": "Add",
}

mf["languages"].en["privacyPolicy.text"] = `
This privacy policy has been compiled to better serve those who are concerned with how their 'Personally identifiable information' (PII) is being used online. PII, as used in privacy law and information security, is information that can be used on its own or with other information to identify, contact, or locate a single person, or to identify an individual in context. Please read our privacy policy carefully to get a clear understanding of how we collect, use, protect or otherwise handle your Personally Identifiable Information in accordance with our website.

**What personal information do we collect from the people that visit our blog, website or app?**

When ordering or registering on our site, as appropriate, you may be asked to enter your name, email address, mailing address or other details to help you with your experience.

**When do we collect information?**

We collect information from you when you register on our site or enter information on our site.
...
```

**Comment by jedwards1211** [comment]
Huh, maybe there's a bug when transpiiling multiline strings like that?  you should be able to take a look at the transpiled output you get without UglifyJS and see if it contains a ` character

**Comment by tomitrescak** [comment]
@jedwards1211 I'm transpiling to ES6. So the ` symbol is preserved in all output *.js files. The weird part is, that it only complains in some of the *.js files, while others are fine.

**Comment by jedwards1211** [comment]
Huh, well, I have no idea if UglifyJS works on ES6.  I wouldn't assume it does; do you know if it's officially supposed to?

**Comment by jedwards1211** [comment]
Is it practical to use some ES6 features in the browser yet?  I haven't really been keeping up with this yet

**Comment by tomitrescak** [comment]
I misunderstood ... it is the babel that does not pick up those template strings and I'm not sure why. Then the uglify freaks out. So it must be a bug in babel as in some files it transpiles template strings to es5 and in some not :/

**Comment by jedwards1211** [comment]
Ah, yeah, I was wondering if it maybe has bugs with multiline ` strings.
