### ISSUE TITLE
Should production mode should use meteor --production flag?

### ISSUE THREAD

**Issue by AdamBrodzinski** [jedwards1211/meteor-webpack-react#6]
I was expecting `npm run prod` to also run Meteor in it's production mode. Is this something that should happen? Or is it beneficial for Meteor to be in dev mode but webpack not? I also wasn't sure if it was just for the React dev/prod or if it's a webpack thing (still learning that lol).

I can submit a PR if this is a wanted thing. It seems to work ok on my build.

**Comment by jedwards1211** [comment]
Oh, how does one run Meteor in production mode?  Is it something different from doing `meteor build` and then running out of the tarball?  I didn't see anything else in the docs, and I'm still learning of course

**Comment by jedwards1211** [comment]
Oh, sorry, I see you mentioned the flag in the title!

**Comment by jedwards1211** [comment]
Yeah, later I'll make that change

**Comment by AdamBrodzinski** [comment]
Ah, so basically it will bundle all of the files into a single js file, mimicking what the production build would be without actually building the tarball. Also certain packages that are dev only (Velocity, Meteor toys, etc..) will not be built or useable. 

the line i'm using is:
` "prod": "(webpack & cd ../meteor && (mv .prod prod || true) && meteor --production &) | cat",`

**Comment by jedwards1211** [comment]
As I mentioned in the other issue, I added the --production flag in the latest push.
