### ISSUE TITLE
I get WARNING messages when I execute "npm install" with node v4.1.1 and npm v2.14.4

### ISSUE THREAD

**Issue by barkbaek** [jedwards1211/meteor-webpack-react#60]
I'm using node v4.1.1 and npm v2.14.4.
When I execute "npm install", I get those warning messages.
___________________________________________________
npm WARN deprecated css-list@0.1.3: Deprecated.
npm WARN optional dep failed, continuing fsevents@1.0.0
npm WARN optional dep failed, continuing fsevents@1.0.0
___________________________________________________

What should I do, if I want to remove the warning messages ?
I'm a meteor guy, but not know well about node.js. Please help me.

**Comment by jedwards1211** [comment]
All I can recommend is `npm ls | grep css-list -B 20` to see what's causing the dependency on a css-list, which is `css-loader`, then file an issue on that project's github.  Not sure if there's a way to turn off warning messages.  In any case they're just warnings, there shouldn't be any problems related to those warnings
