### ISSUE TITLE
After executing ./prod and './met deploy', 'react-transform-hmr' problem occurs.

### ISSUE THREAD

**Issue by barkbaek** [jedwards1211/meteor-webpack-react#61]
In console, warning as

"Uncaught Error: locals[0] does not appear to be a `module` object with Hot Module replacement API enabled. You should disable react-transform-hmr in production by using `env` section in Babel configuration. See the example in README: https://github.com/gaearon/react-transform-hmr".

How can I fix this issue ?

**Comment by jedwards1211** [comment]
we need to fix this, I'll look into it

**Comment by jedwards1211** [comment]
Okay, just fixed this.  If it's difficult to fetch again from this project, just copy the new `.babelrc` from this into your project.
