### ISSUE TITLE
Example folder structure for large projects

### ISSUE THREAD

**Issue by michaltakac** [jedwards1211/meteor-webpack-react#63]
Question: How do you guys structure your react components in large projects when using `meteor-webpack-react`?

Also, should we make a repo for examples with react-router and Flow Router setups? Inspired by these: https://github.com/rackt/react-router/tree/master/examples

Used "huge-apps" example from above (also with useraccounts) and it worked good, but wanted to see how would similar structure look refractored for FlowRouter.

**Comment by AdamBrodzinski** [comment]
Having example apps would be nice but it's a huge burden to keep maintained (as well as diff branches). 

Mostly the same as the example app but more filled out. I store 'pages' components in `pages/posts/PostsNew`, schemas in a `schema/post.js`, action creators in `actions/OnboardingActions.js`.

Checkout the wiki for a flow-router guide:
https://github.com/jedwards1211/meteor-webpack-react/wiki/Using-FlowRouter

React router will be just like any other React app.

**Comment by michaltakac** [comment]
@AdamBrodzinski Sorry for my ignorance, didn't know about the Wiki, thank you!

**Comment by AdamBrodzinski** [comment]
No prob!  I should prob. add that to the readme somewhere lol. 

Closing. feel free to re-open if this doesn't solve your issue :+1:
