### ISSUE TITLE
Problem using SASS with CSS Modules

### ISSUE THREAD

**Issue by ramsaylanier** [jedwards1211/meteor-webpack-react#64]
I want to start off by saying that I think this is an awesome effort here. I'm new to using webpack and CSS Modules, and I think I'm missing something.

I'm attempting to slowly port over an existing app that was original built using the Meteor build with React, Flow Router, and React Layout. I've got the very basics working, and I see my login page gets rendered with the right form - but I can't figure out how to get the css to load. I'm using the sass-loader.

[Here is a link to my repo](https://github.com/ramsaylanier/Meteor-Webpack-Test).  Any thoughts?

**Comment by jedwards1211** [comment]
I don't know what the `ExtractTextPlugin` is for.  Try using the usual `css-loader` and `sass-loader`.

**Comment by AdamBrodzinski** [comment]
It's easiest to leave the CSS in the meteor core folder for migrations... Getting sass global stock to work is a pain. I haven't tried much sass or CSS via webpack so I'm not sure about the spec issue

**Comment by ramsaylanier** [comment]
Yeah, I can get it to work using just css with css-loader and style-loader. Sorry, I forgot to mention that I was trying to use (React-CSS-Modules)[https://github.com/gajus/react-css-modules], which is why you see the ```ExtractTextPlugin```

**Comment by ramsaylanier** [comment]
I've actually got SASS working now, though its compiling it into a style element inside of the head tag. Ideally I was trying to use ```ExtractTextPlugin``` to generate a separate css file, for various reasons. Still can't get that to work. I guess I'll chalk it up to my inexperience with webpack.

**Comment by jedwards1211** [comment]
Yeah, I see now what `ExtractTextPlugin` is for, but I'm sorry, I don't really have any experience with it.  I'm closing this issue as it's not really specific to this project

**Comment by jedwards1211** [comment]
@AdamBrodzinski I always use `sass-loader` in Webpack, and I haven't had any problems.  If you put CSS in the Meteor folder you lose hot reloading of your styles, right?
