### ISSUE TITLE
install fibers error when run test-built script

### ISSUE THREAD

**Issue by bright-sea** [jedwards1211/meteor-webpack-react#65]
Clone this wonderful project, then do a build and when I run test-built, there are some errors:

    > fibers@1.0.5 install /Users/minghaizhao/projects/meteor-webpack- react/dist/bundle/programs/server/node_modules/fibers
    > node ./build.js

    (node) child_process: options.customFds option is deprecated. Use options.stdio instead.
      CXX(target) Release/obj.target/fibers/src/fibers.o
    ../src/fibers.cc:132:44: error: too many arguments to function call, expected at most 2, have 4
                    return Signature::New(isolate, receiver, argc, argv);
                           ~~~~~~~~~~~~~~                    ^~~~~~~~~~
    /Users/minghaizhao/.node-gyp/4.1.1/include/node/v8.h:4675:3: note: 'New' declared here
      static Local<Signature> New(
      ^
    ../src/fibers.cc:140:3: error: no member named 'SetResourceConstraints' in namespace 'v8'; did you mean simply
          'SetResourceConstraints'?
                    v8::SetResourceConstraints(isolate, constraints);
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~
                    SetResourceConstraints
    ../src/fibers.cc:139:7: note: 'SetResourceConstraints' declared here
            void SetResourceConstraints(Isolate* isolate, ResourceConstraints* constraints) {
                 ^
    2 errors generated.

**Comment by jedwards1211** [comment]
This is a C++ compilation error in the Fibers library which is a core dependency of Meteor, it looks like it has nothing to do with this project's config.  If you're having this issue with `meteor-webpack-react` you'll probably have it with any Meteor project, so the first thing to do is `meteor create` a new project, `meteor build` it and see if you can run the bundle that builds.  If there's some difference, check if the created project has a different Meteor version from this one.

**Comment by AdamBrodzinski** [comment]
@bright-sea make sure you're running node 0.10.36  or 0.10.40 for Meteor 1.2. Fibers is not supported in newer Node releases (yet).

**Comment by bright-sea** [comment]
@AdamBrodzinski   Yes, I am using the latest Node releases and this might the reason of the issue. Thanks for the suggestion and will try to use node 0.10.40 instead.

**Comment by bright-sea** [comment]
Just switch back to node 0.10.40 and these errors gone. @AdamBrodzinski 

Thanks!

**Comment by jedwards1211** [comment]
Cool, thanks @AdamBrodzinski!   That's weird, I thought that Meteor downloads and runs whatever version of Node it wants?

**Comment by AdamBrodzinski** [comment]
@jedwards1211 only if you're running the `meteor run` command. Once it's built it's essentially a node app and then it's up to you to ensure the environment is correct. 

If you're not using de-meteorizer I think you also might have to manually set the node version under 'engines' in package.json if you're deploying to a node provider like Nodejitsu or services like that.

Eventually I imagine some hosts and Galaxy will allow you to upload a regular meteor app

**Comment by jedwards1211** [comment]
Oh right!  I wasn't paying attention.  That's cool, I haven't even begin to think about custom Node cloud providers like this.
