### ISSUE TITLE
Run scripts using npm?

### ISSUE THREAD

**Issue by rclai** [jedwards1211/meteor-webpack-react#66]
I noticed that [these scripts](https://github.com/jedwards1211/meteor-webpack-react/blob/6004eb7ab444153934ae492d6fe196e4f1b56a5f/package.json#L35-L39) don't exist.

Would it be cleaner to put those scripts in the root folder into a `scripts` folder and use npm to run them so that you can do `npm dev` instead of `./dev`?

**Comment by jedwards1211** [comment]
Ah, I forgot to remove those.  In the past we did run via `npm` but an obscure issue turned up where `meteor` pegs the CPU from within an `npm run` script: https://github.com/jedwards1211/meteor-webpack-react/issues/13

**Comment by rclai** [comment]
Wow, that is weird, okay.

**Comment by jedwards1211** [comment]
I know, right?
