### ISSUE TITLE
disable minification on Meteor side to speed up prod builds

### ISSUE THREAD

**Issue by jedwards1211** [jedwards1211/meteor-webpack-react#67]
I have done this in my own project, where I use my own package instead of `standard-minifiers` to prevent `*.bundle.js` from getting minified; this way only the webpack UglifyJS plugin performs minification, which I think is faster because it operates per module, instead of on the entire bundle at once.

In my experience, minification can become super slow in large projects.

**Comment by tomitrescak** [comment]
:+1:  it takes a looooong time now;)

**Comment by jbbr** [comment]
Yes I think that's the way to go.

Other idea I had: What about using a webpack plugin to split the server bundle into smaller chunks. If such a plugin would only touch chunks which include contents of changed files meteor would only reload changed chunks.
If that's not possible it could be still an improvement to use a chunk plugin to split vendor code from user core (could be done automatically by crawling package.json) and have a vendor bundle and a server bundle. 
Vendor code wouldn't have to be loaded every time

**Comment by jedwards1211** [comment]
I do still want to investigate loading code into the server out of `webpack-dev-server`, but if that doesn't work code splitting would definitely be nice.  Not sure how what kind of code splitting settings would be appropriate for a skeleton project though (right now there's not really any vendor code), that usually depends on a given project's structure.

**Comment by jedwards1211** [comment]
Also I'd like to eventually make generalized scripts where you say "hey, I want to run this webpack config on the server side in dev mode" (or client side) and it automatically figures out where to put things in Meteor, using the stats from Webpack output to get the list of assets it needs to put into Meteor.

**Comment by jedwards1211** [comment]
@jbbr as far as code splitting on the client side, I need to figure out how to make Meteor serve up the non-entry js bundles as static assets
