### ISSUE TITLE
Server: auto reload broken since server source map support

### ISSUE THREAD

**Issue by jbbr** [jedwards1211/meteor-webpack-react#68]
Since 958be22582b584bb7fc152f213f8611fe4a11441 auto reload of server code is broken.

Steps to reproduce:

1. run ./dev on latest master or 958be22582b584bb7fc152f213f8611fe4a11441
2. See output of meteor methods "sayHello": "Hello from Meteor method!"
3. Change return value of "sayHello" - server bundle is getting updated (terminal shows server.bundle update - but no message from meteor server)
4. reload in brower, return value is still the old ("Hello from Meteor method!")

Somehow the Npm.required server bundle is not watched by meteor but maybe cached? I'm wondering why this doesn't work.

~~By the way: In latest master (not in 958be22582b584bb7fc152f213f8611fe4a11441) client reloads if something on the server is changed. I don't think that's intended?~~ (Not happening anymore, don't know why)

Thanks for adding source map support for the server! It's really the feature I missed the most while using this stack. Hopefully a solution can be found soon :)

**Comment by jbbr** [comment]
For others who can't wait for a better fix i found a hacky workaround:

```bash
npm install --save-dev shelljs on-build-webpack
```

```js
// in webpack.config.server.js
var WebpackOnBuildPlugin = require('on-build-webpack');
require('shelljs/global');

module.exports = {
 ... 
 plugins: [
    new WebpackOnBuildPlugin(function(stats) {
      echo('Adding random string to dummy reload-trigger file');
      ('//' + Math.random().toString()).to('../meteor_core/server/dummy.js');
    }),
  ],
 ....
}

**Comment by jedwards1211** [comment]
Oh duh, of course it wouldn't reload, shoot, sorry I didn't think about that!
I think it may even be possible to run a `webpack-dev-server` client on the server...which would mean even hot reloading on the server.  Of course we'd need some sort of refresh button.  But let me see if I can find a fix for this case...

**Comment by jedwards1211** [comment]
Well, seems like it would be tricky to get source maps to work in any cleaner why that what @jbbr is doing, so I'll just go with a variation of what he's doing.
