### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by tomitrescak** [jedwards1211/meteor-webpack-react#69]
Hi, I'm trying to upgrade my project to the latest version from master, but all my project end up with the same error:

```
W20151005-18:35:26.190(11)? (STDERR) /Users/tomi/.meteor/packages/meteor-tool/.1.1.9.15i59m2++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79
W20151005-18:35:26.190(11)? (STDERR)       obj.forEach(iterator, context);
W20151005-18:35:26.190(11)? (STDERR)           ^
W20151005-18:35:26.190(11)? (STDERR) ReferenceError: require is not defined
```

Any idea what can be causing this?

Thanks!

**Comment by tomitrescak** [comment]
I did not solve it systematically ... instead with a brute force but downloading a clean version from master and copying everything back again ;) Took a while, but all works now. No idea though what it was. Nevermind. Gonna close it.

**Comment by jedwards1211** [comment]
Yeah, I saw this error before.  I made a big change for the server-side source maps: in dev mode, it `Npm.requires` in the server bundle.   In prod mode, it puts `var require = Npm.require;` at the start of the bundle, so that built-in node modules can be required.
