### ISSUE TITLE
Do not deploy/run on error (bail: true?)

### ISSUE THREAD

**Issue by jbbr** [jedwards1211/meteor-webpack-react#71]
I'm using a CI to auto deploy my app after a git push.
To get a "fail" for broken builds in CI I need a non zero exit code from the scripts if something went wrong. The default behavior of webpack on error is currently to just continue and don't throw an error.
This is confusing and will change in webpack-2. See https://github.com/webpack/webpack/issues/708 for details.

To archive the desired behavior I added the `bail: true` to my webpack config files and webpack now fails hard with exit code if something went wrong (like a non existent import).
With the new shelljs scripts, error output is missing because the error from the callback is not printed - Maybe something like `console.error(err.message)` would be a good idea instead of returning silently? Unfortunately console.log of `err` does not look as nice as `stats` from webpack - which seems to be undefined when using bail option and running into an error.

I think that `bail: true` is the desired behavior of a build script and I would suggest enabling it in this skeleton by default and add error output and non-zero exit code to deploy and maybe also run scripts (which should only exit on error on first run obviously)

**Comment by jbbr** [comment]
`bail: true` in config is problematic because the `watch` loop is left on error then.
With the old, direct webpack call it was as easy as adding `--bail` to the webpack call in the `predeploy` script.
Nevertheless I still think that `bail` is the intended and expected behavior in a deploy script - deploying or creating a bundle is not useful after a failed build.

**Comment by jedwards1211** [comment]
@jbbr Ah right, I forgot that if there's a fatal error that won't show up in `console.log(stats.toString(...))`.
It won't be difficult with the new scripts, since they import the webpack configs they can just set `bail: true` on them before passing them to `webpack()` :)

**Comment by jedwards1211** [comment]
@jbbr There's another option though: without `bail: true` being set, non-fatal compile errors *will* show up in the `stats`.  We can catch them there and return the errors from the predeploy script that way

**Comment by jedwards1211** [comment]
@jbbr done, now if there are compile errors they get caught via a `stats.toJson().errors.length` check and printed the pretty way via the usual `stats.toString(...)`.  It also passes an error to the deploy script callback, which does `exit(1)` in such case.

**Comment by jbbr** [comment]
EDIT: okay, nice, you did it almost as I'd wanted to suggest :)

**Comment by jedwards1211** [comment]
And thanks for opening this issue, I haven't used CI tools so I wouldn't have thought of this

**Comment by jbbr** [comment]
One possible problem with this solution:

Are there any relevant non-fatal errors possible? Because then the errors array would be > 1 too and a hard fail might not be intended in this case.

**Comment by jedwards1211** [comment]
I've certainly never seen any soft errors from core Webpack stuff that I'd want to continue from.  Eslint errors would break the build, but that's intended, it's up to the user to configure eslint so that only things they want to break the build are flagged as errors.  I guess the other question is whether the webpack cli (non-watch mode) would return an error code on soft errors?  Let me know if think of any major issues with this though
