### ISSUE TITLE
How to bundle all files of a folder to either client or server?

### ISSUE THREAD

**Issue by rclai** [jedwards1211/meteor-webpack-react#77]
I know this is probably more of a webpack question, but say I created a `publications` folder in my `app` folder, where each publication is defined in a `js` file and I wanted to have all that automatically bundled to my `server.bundle.js`, how would I do that?

**Comment by jedwards1211** [comment]
I don't know of any standard way, but you could always use `fs.readdirSync` to read the files from there in your webpack config and put them in the `entry` array.  Note that requiring them in some kind of loop within one of your modules probably wouldn't work, I doubt Webpack can be smart enough to deduce what a variable passed into `require` is going to be.

**Comment by jedwards1211** [comment]
Whoa, I stand corrected!  I just noticed in @AdamBrodzinski's PR that he found something to do just this!
https://github.com/AdamBrodzinski/meteor-webpack-react/blob/karma-test/test/karma.bundle.js#L2
https://webpack.github.io/docs/context.html

Thanks Adam!

**Comment by rclai** [comment]
Hory shet.

**Comment by rclai** [comment]
Wow it worked so well. This is what I have in my `main_server.js`:

```js
var publicationsContext = require.context('./publications', true, /.+\.js$/);
publicationsContext.keys().forEach(publicationsContext);

var methodsContext = require.context('./methods', true, /.+\.js$/);
methodsContext.keys().forEach(methodsContext);
```

**Comment by AdamBrodzinski** [comment]
Cool just saw this, I never thought about using it for publications :laughing:

**Comment by jedwards1211** [comment]
It's great for loading tests too!

```js
var req = require.context('../', true, /__tests__\/server\/unit\/.*\.jsx?$/);
req.keys().forEach(req);
```

**Comment by ramsaylanier** [comment]
This is rad. Previously, I had been creating index files and then importing * from them. 
So, for example, I would have a Page.js file that imported each individual page and then exported them together as default. In the router i'd import * as Views from './Views.js'.

This seems much better.
