### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by tomitrescak** [jedwards1211/meteor-webpack-react#81]
Guys

Befor, you had tests in your example.
This is no longer the case.
How can I wire up react components tests now to the app?
The only way it worked for me with velocity was to put them in the meteor core directory.
I'm pretty sure @AdamBrodzinski was working on something different.

Thanks!

**Comment by jedwards1211** [comment]
He was, actually I'd never merged his PR because I was being OCD about what I thought was appropriate for a skeleton project.  But I just relented and merged it :)
