### ISSUE TITLE
is this going to load assets on demand ?

### ISSUE THREAD

**Issue by sahanDissanayake** [jedwards1211/meteor-webpack-react#83]
Hi,

Is this going to load scripts/stylesheets/images on demand ?
http://stackoverflow.com/questions/32963760/meteor-and-reactjs-component-loading-on-demand/32980525#32980525

**Comment by jedwards1211** [comment]
It could with small changes to the config, and I'll probably make a demonstration of that in the future.  See https://webpack.github.io/docs/code-splitting.html if you wish to implement it yourself right now.
