### ISSUE TITLE
Making Collections global

### ISSUE THREAD

**Issue by ramsaylanier** [jedwards1211/meteor-webpack-react#85]
I followed your example and created a collections directory inside the app directory, and export/import collection names as needed; however, I really miss being able to debug collections in the console or using a tool like Mongol (from Meteor Toys) because the collection names aren't in the global scope.

I decided to put a lib directory inside the meteor_core directory and include my collections there, so they'd be included in global scope. 

Is there an issue with this? What are the cons? 

Thanks!

**Comment by jedwards1211** [comment]
Everyone's welcome to do whatever they want.  To get access to collections in the console, I do something like:
```js
if (__DEV__) { // webpack DefinePlugin variable
  var global = new Function('return this')();
  global.MyCollection = MyCollection;
}
```
