### ISSUE TITLE
throw new TypeError('Column must be greater than or equal to 0, got '

### ISSUE THREAD

**Issue by gdub01** [jedwards1211/meteor-webpack-react#86]
Just pulled in the latest changes and got this error: 

/node_modules/source-map-support/node_modules/source-map/lib/source-map/source-map-consumer.js:281
W20151007-12:26:26.964(-4)? (STDERR)         throw new TypeError('Column must be greater than or equal to 0, got '
W20151007-12:26:26.964(-4)? (STDERR)               ^
W20151007-12:26:26.964(-4)? (STDERR) TypeError: Column must be greater than or equal to 0, got -23
W20151007-12:26:26.964(-4)? (STDERR)     at SourceMapConsumer_findMapping [as _findMapping] (/Users/Gavin/websites/revise/node_modules/source-map-support/node_modules/source-map/lib/source-map/source-map-consumer.js:281:15)

After googling it looks like it's to do with stack trace or something. However, I'm a bit lost. Has this happened to anyone else?

**Comment by jedwards1211** [comment]
This has to do with using `source-map-support`

**Comment by gdub01** [comment]
$ node -v
v4.1.2
$ npm -v
2.14.4

I updated node and npm (after a ridiculous battle =) ... and it's still throwing the same error. Although I have v.4.1.2...

**Comment by gdub01** [comment]
Actually I found node 0.12 and installed that instead.. also no luck. 
https://github.com/gdub01/mwr-boilerplate - is my repo. It was working before I pulled the changes.

**Comment by gdub01** [comment]
Shoot I installed a fresh copy of your repo and it works perfectly on my computer, so it must be an issue with my code somewhere... but it's weird because it was working before I synced changes.

**Comment by gdub01** [comment]
Okay so I know it's this commit that messes me up: https://github.com/jedwards1211/meteor-webpack-react/commit/37cb658dc609c1a2157d6be22444b1affc37e603

I have so little idea of what it means... But before that commit, my app runs. After, it throws that error.

**Comment by jedwards1211** [comment]
Huh, well I've asked the author of `source-map-support` if I'm using it wrong.  As a workaround for now, you could comment out the line that adds `require('source-map-support/register')` at the top of the bundle: https://github.com/jedwards1211/meteor-webpack-react/blob/master/dev.js#L20.  Of course that would disable source maps but you shouldn't see the error anymore.

**Comment by gdub01** [comment]
Thanks Andy. I'm pretty sure I tried that. I worked on fixing it for about 8 hours yesterday and a couple more today. I also got an expensive lesson in git/remotes/branches =) Anyways, I copied/pasted my components over to a fresh install from here and I just have it setup properly now. I have no idea what the problem was. But it's working great again now. Thanks again!

**Comment by jedwards1211** [comment]
Huh, well, I wouldn't rule out that there could be issues with how I'm using `source-map-support`, so I'll continue trying to investigate it.  Thanks for reporting this!
