### ISSUE TITLE
how can I tell what environment is running?

### ISSUE THREAD

**Issue by rralian** [jedwards1211/meteor-webpack-react#92]
Is there a way to detect within server-side javascript which environment the app is running within? There are settings files, but I'm not sure how to access the data from within a meteor file. I just want the ability to do something like this:
```js
if ( process.env !== 'production' ) return;
```
But when I log out `process.env` within my `main_server.js` file, it just returns an empty object.

**Comment by rralian** [comment]
Nevermind... a little time with node inspector and I was able to find the setting as:
```js
Meteor.settings.public.env
```

**Comment by jedwards1211** [comment]
`if (process.env.NODE_ENV !== 'production') should work too
