### ISSUE TITLE
Why there is two <head> tags on different files?

### ISSUE THREAD

**Issue by gabrielhpugliese** [jedwards1211/meteor-webpack-react#93]
Are there any reason on having `<head>` tag both on `meteor_core/client/loadClientBundle.html` and `meteor_core/meteor.html` or could I merge them?

**Comment by rclai** [comment]
Meteor will merge them automatically.

**Comment by gabrielhpugliese** [comment]
Yes, I've seen it. But why not merge them on files?

**Comment by jbbr** [comment]
Because the script in loadClientBundle.html is only needed for development - loads the js client bundle generated by the webpack-dev-server.
When building for production the scripts ensure that this file is not loaded by meteor.

**Comment by gabrielhpugliese** [comment]
Oh nice! Thanks for explanation!
